import { buildDefaultHrEmail } from "./normalize-job";

export const IT_JOBS = [
  { title: "Summer Internship (June-August)", company: "Google India", location: "Bangalore, Karnataka", salary: "₹50k–1L Month", openings: 100, applicationLink: "https://careers.google.com" },
  { title: "April Fast Track Hiring", company: "Meta India", location: "Mumbai, Maharashtra", salary: "₹20–30 LPA", openings: 50, applicationLink: "https://facebook.com/careers" },
  // ─── TIER 1 IT COMPANIES ───
  { title: "Senior Software Engineer", company: "TCS (Tata Consultancy Services)", location: "Mumbai, Maharashtra", salary: "₹15–22 LPA", openings: 50, applicationLink: "https://nextstep.tcs.com" },
  { title: "Data Scientist", company: "TCS (Tata Consultancy Services)", location: "Hyderabad, Telangana", salary: "₹18–28 LPA", openings: 30, applicationLink: "https://nextstep.tcs.com" },
  { title: "DevOps Engineer", company: "TCS (Tata Consultancy Services)", location: "Chennai, Tamil Nadu", salary: "₹12–20 LPA", openings: 20, applicationLink: "https://nextstep.tcs.com" },
  { title: "Full Stack Developer", company: "Infosys Limited", company2: "", location: "Bangalore, Karnataka", salary: "₹12–18 LPA", openings: 40, applicationLink: "https://www.infosys.com/careers" },
  { title: "Cloud Solutions Architect", company: "Infosys Limited", location: "Pune, Maharashtra", salary: "₹22–35 LPA", openings: 10, applicationLink: "https://www.infosys.com/careers" },
  { title: "AI/ML Engineer", company: "Infosys Limited", location: "Hyderabad, Telangana", salary: "₹20–32 LPA", openings: 15, applicationLink: "https://www.infosys.com/careers" },
  { title: "Senior Software Engineer", company: "Wipro Technologies", location: "Bangalore, Karnataka", salary: "₹18–28 LPA", openings: 12, applicationLink: "https://careers.wipro.com" },
  { title: "Cybersecurity Analyst", company: "Wipro Technologies", location: "Mumbai, Maharashtra", salary: "₹14–22 LPA", openings: 8, applicationLink: "https://careers.wipro.com" },
  { title: "Mobile App Developer", company: "Wipro Technologies", location: "Chennai, Tamil Nadu", salary: "₹10–16 LPA", openings: 15, applicationLink: "https://careers.wipro.com" },
  { title: "UI/UX Designer", company: "Accenture India", location: "Bangalore, Karnataka", salary: "₹10–18 LPA", openings: 20, applicationLink: "https://www.accenture.com/in-en/careers" },
  { title: "Java Backend Developer", company: "Accenture India", location: "Pune, Maharashtra", salary: "₹10–16 LPA", openings: 35, applicationLink: "https://www.accenture.com/in-en/careers" },
  { title: "Power BI / Data Analyst", company: "Accenture India", location: "Chennai, Tamil Nadu", salary: "₹8–14 LPA", openings: 25, applicationLink: "https://www.accenture.com/in-en/careers" },
  { title: "SAP ABAP Consultant", company: "IBM India", location: "Bangalore, Karnataka", salary: "₹16–28 LPA", openings: 7, applicationLink: "https://www.ibm.com/employment/in-en" },
  { title: "Cloud Security Engineer", company: "IBM India", location: "Hyderabad, Telangana", salary: "₹20–35 LPA", openings: 5, applicationLink: "https://www.ibm.com/employment/in-en" },
  { title: "Mainframe Developer", company: "IBM India", location: "Kolkata, West Bengal", salary: "₹12–20 LPA", openings: 8, applicationLink: "https://www.ibm.com/employment/in-en" },
  { title: "React Native Developer", company: "HCL Technologies", location: "Noida, Uttar Pradesh", salary: "₹10–18 LPA", openings: 18, applicationLink: "https://www.hcltech.com/careers" },
  { title: "Network Security Engineer", company: "HCL Technologies", location: "Bangalore, Karnataka", salary: "₹12–20 LPA", openings: 12, applicationLink: "https://www.hcltech.com/careers" },
  { title: "SAP Functional Consultant", company: "HCL Technologies", location: "Chennai, Tamil Nadu", salary: "₹14–24 LPA", openings: 9, applicationLink: "https://www.hcltech.com/careers" },
  // ─── TIER 2 & MNC ───
  { title: "Python Developer", company: "Cognizant Technology Solutions", location: "Bangalore, Karnataka", salary: "₹8–14 LPA", openings: 45, applicationLink: "https://careers.cognizant.com" },
  { title: "RPA Developer (UiPath)", company: "Cognizant Technology Solutions", location: "Mumbai, Maharashtra", salary: "₹10–18 LPA", openings: 20, applicationLink: "https://careers.cognizant.com" },
  { title: "Salesforce Developer", company: "Cognizant Technology Solutions", location: "Hyderabad, Telangana", salary: "₹12–22 LPA", openings: 15, applicationLink: "https://careers.cognizant.com" },
  { title: "Angular Developer", company: "Capgemini India", location: "Mumbai, Maharashtra", salary: "₹8–14 LPA", openings: 30, applicationLink: "https://www.capgemini.com/in-en/careers/" },
  { title: "Test Automation Engineer", company: "Capgemini India", location: "Bangalore, Karnataka", salary: "₹8–16 LPA", openings: 22, applicationLink: "https://www.capgemini.com/in-en/careers/" },
  { title: "Azure Data Engineer", company: "Capgemini India", location: "Pune, Maharashtra", salary: "₹14–24 LPA", openings: 12, applicationLink: "https://www.capgemini.com/in-en/careers/" },
  { title: "Node.js Backend Developer", company: "Tech Mahindra", location: "Hyderabad, Telangana", salary: "₹10–18 LPA", openings: 25, applicationLink: "https://careers.techmahindra.com" },
  { title: "IoT Solutions Engineer", company: "Tech Mahindra", location: "Pune, Maharashtra", salary: "₹12–22 LPA", openings: 10, applicationLink: "https://careers.techmahindra.com" },
  { title: "5G Network Engineer", company: "Tech Mahindra", location: "Bangalore, Karnataka", salary: "₹16–28 LPA", openings: 8, applicationLink: "https://careers.techmahindra.com" },
  { title: "iOS Developer (Swift)", company: "Mphasis Limited", location: "Bangalore, Karnataka", salary: "₹10–18 LPA", openings: 10, applicationLink: "https://www.mphasis.com/careers.html" },
  { title: "Machine Learning Engineer", company: "Mphasis Limited", location: "Bangalore, Karnataka", salary: "₹16–26 LPA", openings: 8, applicationLink: "https://www.mphasis.com/careers.html" },
  { title: "Quality Assurance Engineer", company: "Hexaware Technologies", location: "Mumbai, Maharashtra", salary: "₹6–12 LPA", openings: 35, applicationLink: "https://hexaware.com/careers/" },
  { title: "Kubernetes DevOps Engineer", company: "Hexaware Technologies", location: "Chennai, Tamil Nadu", salary: "₹12–22 LPA", openings: 15, applicationLink: "https://hexaware.com/careers/" },
  { title: "Business Intelligence Analyst", company: "Persistent Systems", location: "Pune, Maharashtra", salary: "₹10–18 LPA", openings: 20, applicationLink: "https://www.persistent.com/careers/" },
  { title: "Blockchain Developer", company: "Persistent Systems", location: "Bangalore, Karnataka", salary: "₹14–26 LPA", openings: 7, applicationLink: "https://www.persistent.com/careers/" },
  { title: "AWS Solutions Architect", company: "Mindtree Ltd", location: "Bangalore, Karnataka", salary: "₹18–30 LPA", openings: 12, applicationLink: "https://www.ltimindtree.com/careers" },
  { title: "Go (Golang) Developer", company: "Mindtree Ltd", location: "Hyderabad, Telangana", salary: "₹14–24 LPA", openings: 8, applicationLink: "https://www.ltimindtree.com/careers" },
  { title: "Embedded Systems Engineer", company: "L&T Technology Services", location: "Bangalore, Karnataka", salary: "₹10–18 LPA", openings: 20, applicationLink: "https://www.ltts.com/careers" },
  { title: "Computer Vision Engineer", company: "L&T Technology Services", location: "Pune, Maharashtra", salary: "₹16–28 LPA", openings: 6, applicationLink: "https://www.ltts.com/careers" },
  { title: "Tableau Developer", company: "Zensar Technologies", location: "Pune, Maharashtra", salary: "₹8–14 LPA", openings: 18, applicationLink: "https://www.zensar.com/careers" },
  { title: "PEGA Developer", company: "Zensar Technologies", location: "Hyderabad, Telangana", salary: "₹10–18 LPA", openings: 12, applicationLink: "https://www.zensar.com/careers" },
  // ─── PRODUCT COMPANIES ───
  { title: "Software Development Engineer (SDE-2)", company: "Amazon India (AWS)", location: "Bangalore, Karnataka", salary: "₹35–60 LPA", openings: 20, applicationLink: "https://amazon.jobs/en/teams/India" },
  { title: "Data Engineer", company: "Amazon India (AWS)", location: "Hyderabad, Telangana", salary: "₹30–50 LPA", openings: 15, applicationLink: "https://amazon.jobs/en/teams/India" },
  { title: "Site Reliability Engineer (SRE)", company: "Google India", location: "Hyderabad, Telangana", salary: "₹45–80 LPA", openings: 8, applicationLink: "https://careers.google.com/jobs" },
  { title: "Android Software Engineer", company: "Google India", location: "Bangalore, Karnataka", salary: "₹40–70 LPA", openings: 10, applicationLink: "https://careers.google.com/jobs" },
  { title: "Software Engineer – Frontend", company: "Microsoft India", location: "Hyderabad, Telangana", salary: "₹35–65 LPA", openings: 15, applicationLink: "https://careers.microsoft.com/v2/global/en/india.html" },
  { title: "Azure Cloud Engineer", company: "Microsoft India", location: "Bangalore, Karnataka", salary: "₹30–55 LPA", openings: 12, applicationLink: "https://careers.microsoft.com/v2/global/en/india.html" },
  { title: "Data Science Lead", company: "Flipkart", location: "Bangalore, Karnataka", salary: "₹28–50 LPA", openings: 10, applicationLink: "https://www.flipkartcareers.com" },
  { title: "Software Engineer – Platform", company: "Flipkart", location: "Bangalore, Karnataka", salary: "₹25–45 LPA", openings: 20, applicationLink: "https://www.flipkartcareers.com" },
  { title: "Backend Engineer (Payments)", company: "Paytm (One97 Communications)", location: "Noida, Uttar Pradesh", salary: "₹18–35 LPA", openings: 25, applicationLink: "https://paytm.com/about-us/careers" },
  { title: "Machine Learning Scientist", company: "Paytm (One97 Communications)", location: "Bangalore, Karnataka", salary: "₹22–40 LPA", openings: 8, applicationLink: "https://paytm.com/about-us/careers" },
  { title: "Full Stack Engineer", company: "Zomato", location: "Gurugram, Haryana", salary: "₹20–38 LPA", openings: 15, applicationLink: "https://www.zomato.com/jobs" },
  { title: "Product Engineer – Ads", company: "Zomato", location: "Gurugram, Haryana", salary: "₹22–40 LPA", openings: 8, applicationLink: "https://www.zomato.com/jobs" },
  { title: "Senior iOS Developer", company: "Swiggy", location: "Bangalore, Karnataka", salary: "₹22–40 LPA", openings: 10, applicationLink: "https://careers.swiggy.com" },
  { title: "Infrastructure Engineer (Kubernetes)", company: "Swiggy", location: "Bangalore, Karnataka", salary: "₹25–42 LPA", openings: 8, applicationLink: "https://careers.swiggy.com" },
  { title: "Software Engineer – Search", company: "Ola (ANI Technologies)", location: "Bangalore, Karnataka", salary: "₹20–38 LPA", openings: 12, applicationLink: "https://careers.olacabs.com" },
  { title: "Data Analyst – Product", company: "Ola (ANI Technologies)", location: "Bangalore, Karnataka", salary: "₹14–25 LPA", openings: 15, applicationLink: "https://careers.olacabs.com" },
  { title: "React.js Developer", company: "Freshworks India", location: "Chennai, Tamil Nadu", salary: "₹16–28 LPA", openings: 20, applicationLink: "https://www.freshworks.com/company/careers/" },
  { title: "Site Reliability Engineer", company: "Freshworks India", location: "Hyderabad, Telangana", salary: "₹20–35 LPA", openings: 10, applicationLink: "https://www.freshworks.com/company/careers/" },
  { title: "Full Stack Java Developer", company: "Zoho Corporation", location: "Chennai, Tamil Nadu", salary: "₹10–20 LPA", openings: 30, applicationLink: "https://careers.zohocorp.com" },
  { title: "Product UI Engineer", company: "Zoho Corporation", location: "Chennai, Tamil Nadu", salary: "₹8–18 LPA", openings: 25, applicationLink: "https://careers.zohocorp.com" },
  { title: "Backend Developer (Rust/Go)", company: "Zerodha", location: "Bangalore, Karnataka", salary: "₹18–35 LPA", openings: 8, applicationLink: "https://zerodha.com/careers" },
  { title: "Data Engineer – Kite", company: "Zerodha", location: "Bangalore, Karnataka", salary: "₹16–30 LPA", openings: 6, applicationLink: "https://zerodha.com/careers" },
  { title: "Software Engineer – Mobile (Flutter)", company: "CRED", location: "Bangalore, Karnataka", salary: "₹22–40 LPA", openings: 10, applicationLink: "https://jobs.lever.co/cred" },
  { title: "Machine Learning Engineer", company: "CRED", location: "Bangalore, Karnataka", salary: "₹25–45 LPA", openings: 6, applicationLink: "https://jobs.lever.co/cred" },
  { title: "Software Engineer (Python/Django)", company: "Razorpay", location: "Bangalore, Karnataka", salary: "₹20–40 LPA", openings: 12, applicationLink: "https://razorpay.com/jobs/" },
  { title: "Security Engineer", company: "Razorpay", location: "Bangalore, Karnataka", salary: "₹22–42 LPA", openings: 7, applicationLink: "https://razorpay.com/jobs/" },
  { title: "NLP Engineer", company: "Sarvam AI", location: "Bangalore, Karnataka", salary: "₹25–50 LPA", openings: 5, applicationLink: "https://sarvam.ai/careers" },
  { title: "LLM Research Scientist", company: "Sarvam AI", location: "Bangalore, Karnataka", salary: "₹30–60 LPA", openings: 4, applicationLink: "https://sarvam.ai/careers" },
  { title: "DevSecOps Engineer", company: "Navi Technologies", location: "Bangalore, Karnataka", salary: "₹18–32 LPA", openings: 8, applicationLink: "https://navi.com/careers" },
  { title: "Senior Data Engineer (Spark)", company: "PhonePe", location: "Bangalore, Karnataka", salary: "₹25–45 LPA", openings: 10, applicationLink: "https://www.phonepe.com/en/careers.html" },
  { title: "Platform Engineer – Infra", company: "PhonePe", location: "Bangalore, Karnataka", salary: "₹28–50 LPA", openings: 8, applicationLink: "https://www.phonepe.com/en/careers.html" },
  { title: "Systems Software Engineer", company: "NVIDIA India", location: "Pune, Maharashtra", salary: "₹35–65 LPA", openings: 6, applicationLink: "https://www.nvidia.com/en-us/about-nvidia/careers/" },
  { title: "VLSI Design Engineer", company: "Qualcomm India", location: "Hyderabad, Telangana", salary: "₹30–55 LPA", openings: 8, applicationLink: "https://www.qualcomm.com/company/careers" },
  { title: "Firmware Engineer", company: "Intel India", location: "Bangalore, Karnataka", salary: "₹28–50 LPA", openings: 10, applicationLink: "https://jobs.intel.com/en" },
  { title: "Network Software Engineer", company: "Cisco India", location: "Bangalore, Karnataka", salary: "₹22–40 LPA", openings: 12, applicationLink: "https://jobs.cisco.com" },
  { title: "Senior Product Manager – API", company: "MathWorks India", location: "Hyderabad, Telangana", salary: "₹30–50 LPA", openings: 5, applicationLink: "https://www.mathworks.com/company/jobs/" },
  { title: "Technical Support Engineer", company: "ServiceNow India", location: "Hyderabad, Telangana", salary: "₹12–22 LPA", openings: 20, applicationLink: "https://careers.servicenow.com" },
  { title: "Enterprise Integration Developer", company: "MuleSoft (Salesforce)", location: "Hyderabad, Telangana", salary: "₹16–28 LPA", openings: 15, applicationLink: "https://salesforce.wd1.myworkdayjobs.com/Salesforce" },
  { title: "DBA – Oracle/PostgreSQL", company: "Oracle India", location: "Bangalore, Karnataka", salary: "₹12–22 LPA", openings: 14, applicationLink: "https://www.oracle.com/corporate/careers/" },
  { title: "Java Microservices Developer", company: "Oracle India", location: "Hyderabad, Telangana", salary: "₹14–24 LPA", openings: 20, applicationLink: "https://www.oracle.com/corporate/careers/" },
  { title: "Senior QA Automation (SDET)", company: "Adobe India", location: "Noida, Uttar Pradesh", salary: "₹18–32 LPA", openings: 10, applicationLink: "https://adobe.wd5.myworkdayjobs.com/external_experienced" },
  { title: "ML Ops Engineer", company: "Adobe India", location: "Bangalore, Karnataka", salary: "₹22–40 LPA", openings: 8, applicationLink: "https://adobe.wd5.myworkdayjobs.com/external_experienced" },
  { title: "Software Engineer – HPC", company: "Siemens India (Technology)", location: "Pune, Maharashtra", salary: "₹14–26 LPA", openings: 12, applicationLink: "https://jobs.siemens.com/careers" },
  { title: "IT Security Analyst", company: "Ernst & Young (EY) India", location: "Bangalore, Karnataka", salary: "₹12–22 LPA", openings: 20, applicationLink: "https://careers.ey.com" },
  { title: "Automation Test Lead", company: "Deloitte India", location: "Hyderabad, Telangana", salary: "₹14–24 LPA", openings: 18, applicationLink: "https://www2.deloitte.com/in/en/careers.html" },
  { title: "Software Engineer (New Graduate)", company: "Intel", location: "Bangalore, Karnataka", salary: "₹18–25 LPA", openings: 30, applicationLink: "https://intel.jobs" },
  { title: "Cloud System Engineer", company: "Oracle", location: "Hyderabad, Telangana", salary: "₹20–30 LPA", openings: 20, applicationLink: "https://oracle.jobs" },
  { title: "QA Engineer (Automation)", company: "Cisco", location: "Pune, Maharashtra", salary: "₹15–25 LPA", openings: 15, applicationLink: "https://cisco.jobs" },
  { title: "React Developer (Remote)", company: "Shopify India", location: "Remote", salary: "₹15–20 LPA", openings: 10, applicationLink: "https://shopify.com/careers" },
  { title: "Backend Engineer (Go)", company: "DigitalOcean", location: "Bangalore, Karnataka", salary: "₹22–35 LPA", openings: 5, applicationLink: "https://digitalocean.com/careers" },
];

export const NONIT_JOBS = [
  { title: "HR Executive", company: "Mahindra Group", location: "Mumbai, Maharashtra", salary: "₹5–8 LPA", openings: 3, applicationLink: "https://careers.mahindra.com" },
  { title: "Talent Acquisition Specialist", company: "Mahindra Group", location: "Pune, Maharashtra", salary: "₹6–10 LPA", openings: 4, applicationLink: "https://careers.mahindra.com" },
  { title: "HRBP Manager", company: "Tata Motors", location: "Mumbai, Maharashtra", salary: "₹12–20 LPA", openings: 3, applicationLink: "https://careers.tatamotors.com" },
  { title: "Industrial Relations Officer", company: "Tata Motors", location: "Pune, Maharashtra", salary: "₹8–14 LPA", openings: 2, applicationLink: "https://careers.tatamotors.com" },
  { title: "Marketing Manager – Digital", company: "ITC Limited", location: "Kolkata, West Bengal", salary: "₹12–18 LPA", openings: 2, applicationLink: "https://www.itcportal.com/about-itc/careers/" },
  { title: "Brand Manager", company: "ITC Limited", location: "Kolkata, West Bengal", salary: "₹14–22 LPA", openings: 2, applicationLink: "https://www.itcportal.com/about-itc/careers/" },
  { title: "Category Manager", company: "Hindustan Unilever Limited", location: "Mumbai, Maharashtra", salary: "₹18–28 LPA", openings: 3, applicationLink: "https://careers.unilever.com" },
  { title: "Supply Chain Manager", company: "Hindustan Unilever Limited", location: "Bangalore, Karnataka", salary: "₹20–32 LPA", openings: 3, applicationLink: "https://careers.unilever.com" },
  { title: "Finance Manager", company: "Hindustan Unilever Limited", location: "Mumbai, Maharashtra", salary: "₹16–26 LPA", openings: 2, applicationLink: "https://careers.unilever.com" },
  { title: "Credit Manager", company: "HDFC Bank", location: "Mumbai, Maharashtra", salary: "₹12–20 LPA", openings: 10, applicationLink: "https://www.hdfcbank.com/personal/about-us/careers" },
  { title: "Branch Manager", company: "HDFC Bank", location: "Bangalore, Karnataka", salary: "₹15–25 LPA", openings: 25, applicationLink: "https://www.hdfcbank.com/personal/about-us/careers" },
  { title: "Relationship Manager – Retail", company: "HDFC Bank", location: "Chennai, Tamil Nadu", salary: "₹8–15 LPA", openings: 50, applicationLink: "https://www.hdfcbank.com/personal/about-us/careers" },
  { title: "Finance Analyst", company: "ICICI Bank", location: "Mumbai, Maharashtra", salary: "₹10–18 LPA", openings: 15, applicationLink: "https://www.icicibankjobs.com" },
  { title: "Risk Manager", company: "ICICI Bank", location: "Hyderabad, Telangana", salary: "₹14–24 LPA", openings: 8, applicationLink: "https://www.icicibankjobs.com" },
  { title: "Corporate Banker", company: "ICICI Bank", location: "Mumbai, Maharashtra", salary: "₹18–30 LPA", openings: 10, applicationLink: "https://www.icicibankjobs.com" },
  { title: "Operations Manager", company: "Reliance Retail", location: "Mumbai, Maharashtra", salary: "₹10–18 LPA", openings: 12, applicationLink: "https://www.ril.com/Our-Businesses/Careers.aspx" },
  { title: "Store Manager", company: "Reliance Retail", location: "Ahmedabad, Gujarat", salary: "₹8–14 LPA", openings: 30, applicationLink: "https://www.ril.com/Our-Businesses/Careers.aspx" },
  { title: "Category Buyer", company: "Reliance Retail", location: "Navi Mumbai, Maharashtra", salary: "₹10–16 LPA", openings: 8, applicationLink: "https://www.ril.com/Our-Businesses/Careers.aspx" },
  { title: "Sales Manager – B2B", company: "Bajaj Finserv", location: "Pune, Maharashtra", salary: "₹10–18 LPA", openings: 20, applicationLink: "https://www.bajajfinserv.in/careers" },
  { title: "Product Manager – Lending", company: "Bajaj Finserv", location: "Pune, Maharashtra", salary: "₹16–28 LPA", openings: 6, applicationLink: "https://www.bajajfinserv.in/careers" },
  { title: "Credit Underwriter", company: "Bajaj Finance Limited", location: "Pune, Maharashtra", salary: "₹8–14 LPA", openings: 25, applicationLink: "https://www.bajajfinserv.in/careers" },
  { title: "Actuarial Analyst", company: "LIC of India", location: "Mumbai, Maharashtra", salary: "₹12–20 LPA", openings: 10, applicationLink: "https://licindia.in/Home/careers" },
  { title: "Financial Advisor", company: "LIC of India", location: "Pan India", salary: "₹4–8 LPA + Commission", openings: 500, applicationLink: "https://licindia.in/Home/careers" },
  { title: "Plant Manager", company: "Maruti Suzuki India", location: "Gurugram, Haryana", salary: "₹25–40 LPA", openings: 3, applicationLink: "https://careers.marutisuzuki.com" },
  { title: "Quality Engineer", company: "Maruti Suzuki India", location: "Manesar, Haryana", salary: "₹8–14 LPA", openings: 20, applicationLink: "https://careers.marutisuzuki.com" },
  { title: "Purchase Manager", company: "Maruti Suzuki India", location: "Gurugram, Haryana", salary: "₹14–24 LPA", openings: 5, applicationLink: "https://careers.marutisuzuki.com" },
  { title: "Civil Engineer – Construction", company: "L&T Construction", location: "Hyderabad, Telangana", salary: "₹8–16 LPA", openings: 30, applicationLink: "https://www.larsentoubro.com/corporate/careers/" },
  { title: "Electrical Engineer", company: "L&T Construction", location: "Chennai, Tamil Nadu", salary: "₹8–15 LPA", openings: 25, applicationLink: "https://www.larsentoubro.com/corporate/careers/" },
  { title: "Project Manager – Infrastructure", company: "L&T Construction", location: "Mumbai, Maharashtra", salary: "₹20–35 LPA", openings: 5, applicationLink: "https://www.larsentoubro.com/corporate/careers/" },
  { title: "Content Marketing Manager", company: "Byju's", location: "Bangalore, Karnataka", salary: "₹8–16 LPA", openings: 10, applicationLink: "https://byjus.com/careers/" },
  { title: "Academic Mentor", company: "Byju's", location: "Pan India", salary: "₹5–9 LPA", openings: 200, applicationLink: "https://byjus.com/careers/" },
  { title: "Business Development Executive", company: "Byju's", location: "Bangalore, Karnataka", salary: "₹6–12 LPA", openings: 50, applicationLink: "https://byjus.com/careers/" },
  { title: "Warehouse Manager", company: "Amazon Logistics India", location: "Delhi NCR", salary: "₹8–14 LPA", openings: 15, applicationLink: "https://www.amazon.jobs/en/locations/india" },
  { title: "Operations Executive", company: "Delhivery Ltd", location: "Mumbai, Maharashtra", salary: "₹4–7 LPA", openings: 40, applicationLink: "https://www.delhivery.com/careers" },
  { title: "Logistics Manager", company: "Delhivery Ltd", location: "Delhi NCR", salary: "₹10–18 LPA", openings: 8, applicationLink: "https://www.delhivery.com/careers" },
  { title: "Account Manager – Corporate", company: "Blue Dart Express", location: "Mumbai, Maharashtra", salary: "₹8–15 LPA", openings: 12, applicationLink: "https://www.bluedart.com/aboutbluedart-careers" },
  { title: "Sales Territory Manager", company: "Nestlé India", location: "Gurgaon, Haryana", salary: "₹8–14 LPA", openings: 20, applicationLink: "https://www.nestle.in/jobs" },
  { title: "Brand Manager – FMCG", company: "Nestlé India", location: "Gurgaon, Haryana", salary: "₹14–24 LPA", openings: 4, applicationLink: "https://www.nestle.in/jobs" },
  { title: "Finance Executive", company: "Adani Group", location: "Ahmedabad, Gujarat", salary: "₹8–16 LPA", openings: 20, applicationLink: "https://www.adani.com/careers" },
  { title: "Legal Counsel – Commercial", company: "Adani Group", location: "Ahmedabad, Gujarat", salary: "₹15–28 LPA", openings: 4, applicationLink: "https://www.adani.com/careers" },
  { title: "Corporate Affairs Manager", company: "Adani Group", location: "Mumbai, Maharashtra", salary: "₹14–24 LPA", openings: 3, applicationLink: "https://www.adani.com/careers" },
  { title: "Insurance Sales Officer", company: "HDFC Life Insurance", location: "Bangalore, Karnataka", salary: "₹4–7 LPA + Commission", openings: 60, applicationLink: "https://hdfc-life.kenexa.com/psp/hdfclife" },
  { title: "Product Actuary", company: "HDFC Life Insurance", location: "Mumbai, Maharashtra", salary: "₹18–30 LPA", openings: 5, applicationLink: "https://hdfc-life.kenexa.com/psp/hdfclife" },
  { title: "Retail Banker", company: "Axis Bank", location: "Bangalore, Karnataka", salary: "₹6–12 LPA", openings: 35, applicationLink: "https://www.axisbank.com/about-us/careers" },
  { title: "Trade Finance Officer", company: "Axis Bank", location: "Mumbai, Maharashtra", salary: "₹10–18 LPA", openings: 8, applicationLink: "https://www.axisbank.com/about-us/careers" },
  { title: "MEP Engineer", company: "SOBHA Developers", location: "Bangalore, Karnataka", salary: "₹8–14 LPA", openings: 15, applicationLink: "https://www.sobha.com/careers/" },
  { title: "Site Engineer – Civil", company: "SOBHA Developers", location: "Hyderabad, Telangana", salary: "₹6–10 LPA", openings: 20, applicationLink: "https://www.sobha.com/careers/" },
  { title: "Customer Experience Lead", company: "SpiceJet", location: "Gurugram, Haryana", salary: "₹8–14 LPA", openings: 10, applicationLink: "https://www.spicejet.com/careers" },
  { title: "Revenue Manager – Airlines", company: "SpiceJet", location: "Gurugram, Haryana", salary: "₹14–24 LPA", openings: 4, applicationLink: "https://www.spicejet.com/careers" },
  { title: "Hotel Operations Manager", company: "Taj Hotels (IHCL)", location: "Mumbai, Maharashtra", salary: "₹12–22 LPA", openings: 6, applicationLink: "https://www.tajhotels.com/en-in/careers/" },
  { title: "Food & Beverage Manager", company: "OYO Rooms", location: "Gurugram, Haryana", salary: "₹8–14 LPA", openings: 12, applicationLink: "https://jobs.oyorooms.com" },
  { title: "Recruitment Specialist", company: "TeamLease Services", location: "Bangalore, Karnataka", salary: "₹5–9 LPA", openings: 25, applicationLink: "https://www.teamlease.com/careers" },
  { title: "Staffing Account Manager", company: "Quess Corp", location: "Bangalore, Karnataka", salary: "₹7–13 LPA", openings: 15, applicationLink: "https://www.quesscorp.com/careers/" },
  { title: "Mechanical Design Engineer", company: "Bosch India", location: "Bangalore, Karnataka", salary: "₹8–16 LPA", openings: 20, applicationLink: "https://www.bosch.in/careers/" },
  { title: "Production Supervisor", company: "Bosch India", location: "Nashik, Maharashtra", salary: "₹6–10 LPA", openings: 15, applicationLink: "https://www.bosch.in/careers/" },
  { title: "Strategic Sourcing Manager", company: "3M India", location: "Bangalore, Karnataka", salary: "₹15–26 LPA", openings: 4, applicationLink: "https://3m.wd1.myworkdayjobs.com/3M" },
  { title: "Research Analyst", company: "CRISIL (S&P Global)", location: "Mumbai, Maharashtra", salary: "₹8–14 LPA", openings: 20, applicationLink: "https://www.crisil.com/en/home/careers.html" },
  { title: "Equity Research Analyst", company: "Motilal Oswal Financial Services", location: "Mumbai, Maharashtra", salary: "₹10–20 LPA", openings: 8, applicationLink: "https://www.motilaloswal.com/investor-relations/careers" },
  { title: "Commodity Trader", company: "MCX (Multi Commodity Exchange)", location: "Mumbai, Maharashtra", salary: "₹10–20 LPA", openings: 6, applicationLink: "https://www.mcxindia.com/about-us/career" },
  { title: "Fundraising Manager – NGO", company: "CRY (Child Rights & You)", location: "Mumbai, Maharashtra", salary: "₹6–10 LPA", openings: 5, applicationLink: "https://www.cry.org/work-with-us" },
  { title: "Public Relations Manager", company: "Adfactors PR", location: "Bangalore, Karnataka", salary: "₹8–15 LPA", openings: 7, applicationLink: "https://www.adfactorspr.com/careers" },
  { title: "Creative Director", company: "McCann Worldgroup India", location: "Mumbai, Maharashtra", salary: "₹18–32 LPA", openings: 3, applicationLink: "https://www.mccann.com/careers" },
  { title: "Account Planner", company: "Ogilvy India", location: "Mumbai, Maharashtra", salary: "₹10–18 LPA", openings: 5, applicationLink: "https://www.ogilvy.com/careers" },
  { title: "Media Planner – Digital", company: "WPP India (GroupM)", location: "Mumbai, Maharashtra", salary: "₹8–15 LPA", openings: 12, applicationLink: "https://www.wpp.com/people/jobs" },
  { title: "Event Manager", company: "Wizcraft International", location: "Mumbai, Maharashtra", salary: "₹6–12 LPA", openings: 8, applicationLink: "https://www.wizcraft.com/careers" },
  { title: "Healthcare Administrator", company: "Apollo Hospitals", location: "Hyderabad, Telangana", salary: "₹6–12 LPA", openings: 15, applicationLink: "https://www.apollohospitals.com/careers/" },
  { title: "Hospital Operations Manager", company: "Fortis Healthcare", location: "Gurugram, Haryana", salary: "₹10–18 LPA", openings: 8, applicationLink: "https://www.fortishealthcare.com/careers" },
  { title: "Medical Representative", company: "Cipla Limited", location: "Pan India", salary: "₹4–7 LPA", openings: 150, applicationLink: "https://www.cipla.com/careers" },
  { title: "Regulatory Affairs Manager", company: "Dr. Reddy's Laboratories", location: "Hyderabad, Telangana", salary: "₹12–22 LPA", openings: 8, applicationLink: "https://careers.drreddys.com" },
  { title: "Production Chemist", company: "Sun Pharmaceutical", location: "Vadodara, Gujarat", salary: "₹6–10 LPA", openings: 25, applicationLink: "https://www.sunpharma.com/careers" },
  { title: "Quality Control Analyst", company: "Biocon Limited", location: "Bangalore, Karnataka", salary: "₹6–12 LPA", openings: 20, applicationLink: "https://www.biocon.com/careers/" },
  { title: "Sales Executive – Agri", company: "UPL Limited", location: "Mumbai, Maharashtra", salary: "₹5–9 LPA", openings: 40, applicationLink: "https://www.upl-ltd.com/careers" },
  { title: "ESG Analyst", company: "Tata Sustainability Group", location: "Mumbai, Maharashtra", salary: "₹10–18 LPA", openings: 5, applicationLink: "https://careers.tata.com" },
  { title: "Treasury Manager", company: "Infosys BPM", location: "Mysore, Karnataka", salary: "₹14–24 LPA", openings: 5, applicationLink: "https://www.infosys.com/bpm/about/careers.html" },
  { title: "Chartered Accountant (CA)", company: "Deloitte India", location: "Bangalore, Karnataka", salary: "₹14–24 LPA", openings: 20, applicationLink: "https://www2.deloitte.com/in/en/careers.html" },
  { title: "Tax Consultant", company: "PricewaterhouseCoopers India", location: "Mumbai, Maharashtra", salary: "₹12–22 LPA", openings: 15, applicationLink: "https://www.pwc.in/careers.html" },
  { title: "Management Consultant", company: "McKinsey & Company India", location: "Gurugram, Haryana", salary: "₹25–50 LPA", openings: 8, applicationLink: "https://www.mckinsey.com/careers" },
  { title: "Strategy Analyst", company: "Boston Consulting Group India", location: "Mumbai, Maharashtra", salary: "₹20–40 LPA", openings: 6, applicationLink: "https://careers.bcg.com" },
  { title: "Corporate Lawyer", company: "Cyril Amarchand Mangaldas", location: "Mumbai, Maharashtra", salary: "₹15–30 LPA", openings: 8, applicationLink: "https://www.cyrilshroff.com/careers/" },
  { title: "Intellectual Property Attorney", company: "Anand & Anand (IP Law Firm)", location: "Noida, Uttar Pradesh", salary: "₹10–20 LPA", openings: 5, applicationLink: "https://www.anandandanand.com/careers.html" },
  { title: "Compliance Officer – SEBI", company: "SEBI Registered Intermediary", location: "Mumbai, Maharashtra", salary: "₹12–20 LPA", openings: 10, applicationLink: "https://www.sebi.gov.in/sebiweb/home/HomeAction.do?doListing=yes&sid=5&ssid=9&smid=0" },
  { title: "Fashion Merchandiser", company: "Myntra (Flipkart)", location: "Bangalore, Karnataka", salary: "₹8–15 LPA", openings: 10, applicationLink: "https://careers.myntra.com" },
  { title: "Buyer – Private Label", company: "Nykaa Fashion", location: "Mumbai, Maharashtra", salary: "₹10–18 LPA", openings: 6, applicationLink: "https://careers.nykaa.com" },
  { title: "Travel Consultant", company: "MakeMyTrip", location: "Gurugram, Haryana", salary: "₹6–12 LPA", openings: 20, applicationLink: "https://careers.makemytrip.com" },
  { title: "Cluster Operations Manager", company: "BigBasket (Tata Digital)", location: "Bangalore, Karnataka", salary: "₹10–18 LPA", openings: 8, applicationLink: "https://careers.bigbasket.com" },
  { title: "Business Analyst – ERP", company: "SAP India", location: "Gurugram, Haryana", salary: "₹14–26 LPA", openings: 12, applicationLink: "https://jobs.sap.com/go/sap-india-jobs" },
];

export const STATE_GOVT_JOBS = [
  { title: "Junior Engineer (Civil) – PWD", company: "Karnataka PWD (KPSC)", location: "Pan Karnataka", salary: "₹27,300–52,650/month", openings: 250, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Junior Engineer (Electrical) – PWD", company: "Karnataka PWD (KPSC)", location: "Pan Karnataka", salary: "₹27,300–52,650/month", openings: 150, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Junior Engineer (Mechanical)", company: "Karnataka PWD (KPSC)", location: "Pan Karnataka", salary: "₹27,300–52,650/month", openings: 80, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Assistant Engineer (Civil)", company: "Karnataka Water Resources Dept (KPSC)", location: "Bangalore, Karnataka", salary: "₹34,500–62,000/month", openings: 120, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Police Sub Inspector (PSI) – Civil", company: "Karnataka State Police (KPSC)", location: "Pan Karnataka", salary: "₹35,100–62,600/month", openings: 545, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Police Sub Inspector (PSI) – Armed", company: "Karnataka State Police (KPSC)", location: "Pan Karnataka", salary: "₹35,100–62,600/month", openings: 200, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Police Constable (Civil)", company: "Karnataka State Police", location: "Pan Karnataka", salary: "₹21,400–42,000/month", openings: 3000, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Police Constable (Armed)", company: "Karnataka State Police", location: "Pan Karnataka", salary: "₹21,400–42,000/month", openings: 1500, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Staff Nurse (ANM) – District Hospitals", company: "Karnataka Health Dept (DHO)", location: "Pan Karnataka", salary: "₹22,400–42,500/month", openings: 1200, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Staff Nurse – PHC", company: "Karnataka Health Dept (DHO)", location: "Rural Karnataka", salary: "₹22,400–42,500/month", openings: 800, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Lab Technician – Government Hospitals", company: "Karnataka Health Dept (DHO)", location: "Pan Karnataka", salary: "₹18,000–35,000/month", openings: 350, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Pharmacist – Government Hospitals", company: "Karnataka Health Dept (DHO)", location: "Pan Karnataka", salary: "₹20,000–38,000/month", openings: 400, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "ASHA Worker", company: "Karnataka NHM", location: "Rural Karnataka", salary: "₹4,000–8,000/month", openings: 5000, applicationLink: "https://nhm.kar.nic.in" },
  { title: "Medical Officer – Primary Health Center", company: "Karnataka Health Dept (KPSC)", location: "Rural Karnataka", salary: "₹56,100–1,32,000/month", openings: 300, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Specialist Doctor (Gynaecology)", company: "Karnataka Health Dept (KPSC)", location: "District Hospitals", salary: "₹67,700–1,52,000/month", openings: 80, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Assistant Professor – Computer Science", company: "Karnataka Examinations Authority (KEA)", location: "Government Engineering Colleges", salary: "₹37,400–67,000/month", openings: 85, applicationLink: "https://kea.kar.nic.in" },
  { title: "Assistant Professor – Electronics & Communication", company: "Karnataka Examinations Authority (KEA)", location: "Government Engineering Colleges", salary: "₹37,400–67,000/month", openings: 75, applicationLink: "https://kea.kar.nic.in" },
  { title: "Assistant Professor – Mechanical Engineering", company: "Karnataka Examinations Authority (KEA)", location: "Government Engineering Colleges", salary: "₹37,400–67,000/month", openings: 65, applicationLink: "https://kea.kar.nic.in" },
  { title: "Assistant Professor – Civil Engineering", company: "Karnataka Examinations Authority (KEA)", location: "Government Engineering Colleges", salary: "₹37,400–67,000/month", openings: 60, applicationLink: "https://kea.kar.nic.in" },
  { title: "Assistant Professor – Mathematics", company: "Karnataka Examinations Authority (KEA)", location: "Government First Grade Colleges", salary: "₹37,400–67,000/month", openings: 120, applicationLink: "https://kea.kar.nic.in" },
  { title: "Assistant Professor – Physics", company: "Karnataka Examinations Authority (KEA)", location: "Government First Grade Colleges", salary: "₹37,400–67,000/month", openings: 100, applicationLink: "https://kea.kar.nic.in" },
  { title: "Assistant Professor – Chemistry", company: "Karnataka Examinations Authority (KEA)", location: "Government First Grade Colleges", salary: "₹37,400–67,000/month", openings: 90, applicationLink: "https://kea.kar.nic.in" },
  { title: "PGT Teacher (Computer Science)", company: "Karnataka Residential Schools (KREIS)", location: "Pan Karnataka", salary: "₹28,900–46,900/month", openings: 150, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "PGT Teacher (Kannada)", company: "Karnataka Residential Schools (KREIS)", location: "Pan Karnataka", salary: "₹28,900–46,900/month", openings: 200, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "TGT Teacher (English Medium)", company: "Samagra Shiksha Karnataka", location: "Pan Karnataka", salary: "₹22,400–42,500/month", openings: 500, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "TGT Teacher (Mathematics)", company: "Samagra Shiksha Karnataka", location: "Pan Karnataka", salary: "₹22,400–42,500/month", openings: 450, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "High School Teacher – Science", company: "Karnataka Education Dept (KPSC)", location: "Pan Karnataka", salary: "₹25,000–48,000/month", openings: 600, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Primary School Teacher", company: "Karnataka Education Dept (KPSC)", location: "Rural Karnataka", salary: "₹18,000–35,000/month", openings: 1500, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Commercial Tax Inspector (GST)", company: "Karnataka Commercial Taxes Dept (KPSC)", location: "Bangalore / Mysore / Hubli", salary: "₹28,100–56,900/month", openings: 120, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Asst. Commercial Tax Officer", company: "Karnataka Commercial Taxes Dept (KPSC)", location: "Pan Karnataka", salary: "₹25,500–48,000/month", openings: 200, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Agriculture Officer", company: "Karnataka Dept of Agriculture (KPSC)", location: "Rural Karnataka (All Districts)", salary: "₹25,500–48,000/month", openings: 300, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Horticulture Officer", company: "Karnataka Horticulture Dept", location: "Pan Karnataka", salary: "₹25,500–48,000/month", openings: 120, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Veterinary Officer", company: "Karnataka Animal Husbandry Dept (KPSC)", location: "Rural Karnataka", salary: "₹28,900–46,900/month", openings: 180, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Forest Range Officer", company: "Karnataka Forest Dept (KPSC)", location: "Forest Zones, Karnataka", salary: "₹28,100–56,900/month", openings: 80, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Deputy Range Forest Officer", company: "Karnataka Forest Dept (KPSC)", location: "Western Ghats, Karnataka", salary: "₹25,500–48,000/month", openings: 60, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Revenue Inspector", company: "Karnataka Revenue Dept (KPSC)", location: "Pan Karnataka (Taluk Level)", salary: "₹21,400–42,000/month", openings: 400, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Village Accountant", company: "Karnataka Revenue Dept (KPSC)", location: "Rural Karnataka", salary: "₹18,000–35,000/month", openings: 800, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Tahsildar (Group A)", company: "Karnataka Revenue Dept (KPSC)", location: "Taluk Headquarters, Karnataka", salary: "₹34,500–62,000/month", openings: 60, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Deputy Commissioner (UPSC/KPSC)", company: "Karnataka Administrative Service (IAS Cadre)", location: "District Headquarters", salary: "₹56,100–1,32,000/month", openings: 20, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Section Officer – Sachivalaya", company: "Karnataka Secretariat (KPSC)", location: "Vidhana Soudha, Bangalore", salary: "₹28,100–56,900/month", openings: 150, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Assistant Section Officer", company: "Karnataka Secretariat (KPSC)", location: "Vidhana Soudha, Bangalore", salary: "₹22,400–42,500/month", openings: 250, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Gazetted Probationer (KAS)", company: "Karnataka Administrative Service (KPSC)", location: "Pan Karnataka", salary: "₹34,500–62,000/month", openings: 120, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Transport Inspector (RTO)", company: "Karnataka Transport Dept (RTO)", location: "District RTOs, Karnataka", salary: "₹25,500–48,000/month", openings: 80, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Motor Vehicle Inspector", company: "Karnataka Transport Dept (RTO)", location: "Pan Karnataka", salary: "₹21,400–42,000/month", openings: 120, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Sub Registrar – Registration Dept", company: "Karnataka Registration Dept (KPSC)", location: "Sub-Registrar Offices", salary: "₹28,100–56,900/month", openings: 90, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Junior Registrar – Cooperative Societies", company: "Karnataka Cooperative Dept", location: "Pan Karnataka", salary: "₹25,500–48,000/month", openings: 60, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Excise Sub Inspector", company: "Karnataka Excise Dept (KPSC)", location: "Pan Karnataka", salary: "₹28,100–56,900/month", openings: 100, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Drug Inspector", company: "Karnataka Food & Drug Dept", location: "District Offices, Karnataka", salary: "₹28,900–46,900/month", openings: 60, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Food Safety Officer", company: "Karnataka Food Safety Dept", location: "Pan Karnataka", salary: "₹25,500–48,000/month", openings: 80, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Asst Director – Town Planning", company: "Karnataka Town Planning Dept", location: "Bangalore Urban / Mysore", salary: "₹34,500–62,000/month", openings: 30, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "BBMP Assistant Executive Engineer", company: "Bruhat Bengaluru Mahanagara Palike", location: "Bangalore, Karnataka", salary: "₹34,500–62,000/month", openings: 40, applicationLink: "https://bbmp.gov.in/careers" },
  { title: "BBMP Health Inspector", company: "Bruhat Bengaluru Mahanagara Palike", location: "Bangalore, Karnataka", salary: "₹21,400–42,000/month", openings: 80, applicationLink: "https://bbmp.gov.in/careers" },
  { title: "BESCOM Junior Engineer (Electrical)", company: "Bangalore Electricity Supply Company (BESCOM)", location: "Bangalore, Karnataka", salary: "₹27,300–52,650/month", openings: 200, applicationLink: "https://www.bescom.co.in/careers" },
  { title: "BMRCL Station Controller", company: "Bangalore Metro Rail Corporation (BMRCL)", location: "Bangalore, Karnataka", salary: "₹28,900–46,900/month", openings: 100, applicationLink: "https://www.bmrc.co.in/recruitment" },
  { title: "BMRCL Junior Engineer (Civil/Electrical)", company: "Bangalore Metro Rail Corporation (BMRCL)", location: "Bangalore, Karnataka", salary: "₹27,300–52,650/month", openings: 60, applicationLink: "https://www.bmrc.co.in/recruitment" },
  { title: "KSRTC Driver – Stage Carriage", company: "Karnataka State Road Transport Corp (KSRTC)", location: "Pan Karnataka", salary: "₹18,000–35,000/month", openings: 2000, applicationLink: "https://ksrtc.in/oprs-web/career.do" },
  { title: "KSRTC Conductor", company: "Karnataka State Road Transport Corp (KSRTC)", location: "Pan Karnataka", salary: "₹16,000–30,000/month", openings: 3000, applicationLink: "https://ksrtc.in/oprs-web/career.do" },
  { title: "KSRTC Assistant Traffic Inspector", company: "Karnataka State Road Transport Corp (KSRTC)", location: "Pan Karnataka", salary: "₹22,400–42,500/month", openings: 150, applicationLink: "https://ksrtc.in/oprs-web/career.do" },
  { title: "Karnataka Power Transmission Corp – AEE", company: "KPTCL (Karnataka Power Corp)", location: "Pan Karnataka", salary: "₹34,500–62,000/month", openings: 80, applicationLink: "https://kptcl.karnataka.gov.in" },
  { title: "KPCC – Junior Engineer (Power)", company: "Karnataka Power Corporation (KPCL)", location: "Power Stations, Karnataka", salary: "₹27,300–52,650/month", openings: 120, applicationLink: "https://kpcl.karnataka.gov.in" },
  { title: "KUWSDB Assistant Engineer", company: "Karnataka Urban Water Supply & Drainage Board", location: "Urban Karnataka", salary: "₹34,500–62,000/month", openings: 50, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "WALMI Junior Engineer (Irrigation)", company: "Water and Land Management Institute Karnataka", location: "Dharwad, Karnataka", salary: "₹27,300–52,650/month", openings: 40, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "BMTC Inspector", company: "Bangalore Metropolitan Transport Corp (BMTC)", location: "Bangalore, Karnataka", salary: "₹25,500–48,000/month", openings: 80, applicationLink: "https://bmtcinfo.com/careers" },
  { title: "Librarian – Government College", company: "Karnataka Education Dept (KPSC)", location: "Government Colleges, Karnataka", salary: "₹21,400–42,000/month", openings: 100, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Physical Education Teacher", company: "Karnataka Education Dept (KPSC)", location: "Government Schools, Karnataka", salary: "₹22,400–42,500/month", openings: 200, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Social Welfare Inspector", company: "Karnataka Social Welfare Dept", location: "Pan Karnataka", salary: "₹21,400–42,000/month", openings: 150, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "District Social Welfare Officer", company: "Karnataka Social Welfare Dept", location: "District Headquarters", salary: "₹28,100–56,900/month", openings: 30, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Probation Officer – Juvenile Justice", company: "Karnataka Child Development Dept", location: "Pan Karnataka", salary: "₹25,500–48,000/month", openings: 60, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Irrigation Supervisor", company: "Karnataka Irrigation Dept (KPSC)", location: "Cauvery Basin, Karnataka", salary: "₹21,400–42,000/month", openings: 100, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Statistician – State Planning Dept", company: "Karnataka State Planning Commission", location: "Bangalore, Karnataka", salary: "₹25,500–48,000/month", openings: 40, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Economic Officer", company: "Karnataka Economic Dept (KPSC)", location: "Bangalore, Karnataka", salary: "₹28,100–56,900/month", openings: 30, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Audit Inspector – CAG Karnataka", company: "Principal Accountant General Karnataka", location: "Bangalore, Karnataka", salary: "₹25,500–48,000/month", openings: 60, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Asst. Controller Legal Metrology", company: "Karnataka Legal Metrology Dept", location: "Pan Karnataka", salary: "₹25,500–48,000/month", openings: 50, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Mines Inspector", company: "Karnataka Mines & Geology Dept (KPSC)", location: "Bellary / Chitradurga", salary: "₹28,100–56,900/month", openings: 40, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "KLDB Asst. Manager (Dairy)", company: "Karnataka Livestock Development Board", location: "Pan Karnataka", salary: "₹28,100–56,900/month", openings: 30, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Fisheries Inspector", company: "Karnataka Fisheries Dept", location: "Coastal Karnataka", salary: "₹21,400–42,000/month", openings: 60, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Junior Information Officer (PIB Karnataka)", company: "Karnataka Information Dept", location: "Bangalore, Karnataka", salary: "₹25,500–48,000/month", openings: 40, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "District Information Officer", company: "Karnataka Information Dept", location: "District HQs, Karnataka", salary: "₹28,100–56,900/month", openings: 30, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Archaeology Supervisor", company: "Karnataka Dept of Archaeology", location: "Hampi / Badami, Karnataka", salary: "₹21,400–42,000/month", openings: 20, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Fingerprint Expert", company: "Karnataka State Forensic Science Lab", location: "Bangalore, Karnataka", salary: "₹25,500–48,000/month", openings: 30, applicationLink: "https://kpsc.kar.nic.in" },
  { title: "Sericulture Inspector", company: "Karnataka Dept of Sericulture", location: "Hassan / Chikkaballapur", salary: "₹21,400–42,000/month", openings: 50, applicationLink: "https://kpsc.kar.nic.in" },
];

export const CENTRAL_GOVT_JOBS = [
  { title: "SSC CGL – Income Tax Inspector", company: "Staff Selection Commission (SSC)", location: "Pan India", salary: "₹44,900–1,42,400/month", openings: 3000, applicationLink: "https://ssc.gov.in" },
  { title: "SSC CGL – Assistant Section Officer (CSS)", company: "Staff Selection Commission (SSC)", location: "New Delhi", salary: "₹44,900–1,42,400/month", openings: 2500, applicationLink: "https://ssc.gov.in" },
  { title: "SSC CGL – Sub Inspector (CBI)", company: "Staff Selection Commission (SSC)", location: "Pan India", salary: "₹35,400–1,12,400/month", openings: 500, applicationLink: "https://ssc.gov.in" },
  { title: "SSC CGL – Statistical Investigator Grade II", company: "Staff Selection Commission (SSC)", location: "Pan India", salary: "₹35,400–1,12,400/month", openings: 400, applicationLink: "https://ssc.gov.in" },
  { title: "SSC CGL – Auditor (CAG/CGDA)", company: "Staff Selection Commission (SSC)", location: "Pan India", salary: "₹29,200–92,300/month", openings: 1500, applicationLink: "https://ssc.gov.in" },
  { title: "SSC CGL – Accountant (CGA)", company: "Staff Selection Commission (SSC)", location: "Pan India", salary: "₹29,200–92,300/month", openings: 1200, applicationLink: "https://ssc.gov.in" },
  { title: "SSC CGL – Junior Statistical Officer", company: "Staff Selection Commission (SSC)", location: "Pan India", salary: "₹35,400–1,12,400/month", openings: 600, applicationLink: "https://ssc.gov.in" },
  { title: "SSC CHSL – LDC / JSA", company: "Staff Selection Commission (SSC)", location: "Pan India", salary: "₹19,900–63,200/month", openings: 6000, applicationLink: "https://ssc.gov.in" },
  { title: "SSC CHSL – Postal Assistant / Sorting Assistant", company: "Staff Selection Commission (SSC)", location: "Pan India", salary: "₹25,500–81,100/month", openings: 4000, applicationLink: "https://ssc.gov.in" },
  { title: "SSC CHSL – Data Entry Operator (DEO)", company: "Staff Selection Commission (SSC)", location: "Pan India", salary: "₹25,500–81,100/month", openings: 3000, applicationLink: "https://ssc.gov.in" },
  { title: "SSC MTS – Multi Tasking Staff", company: "Staff Selection Commission (SSC)", location: "Pan India", salary: "₹18,000–56,900/month", openings: 15000, applicationLink: "https://ssc.gov.in" },
  { title: "SSC CPO – Sub Inspector (CAPF/BSF/CRPF)", company: "Staff Selection Commission (SSC)", location: "Pan India", salary: "₹35,400–1,12,400/month", openings: 2000, applicationLink: "https://ssc.gov.in" },
  { title: "SSC GD Constable – CISF/BSF/CRPF/SSB/Assam Rifles", company: "Staff Selection Commission (SSC)", location: "Pan India", salary: "₹21,700–69,100/month", openings: 50000, applicationLink: "https://ssc.gov.in" },
  { title: "SSC JE – Junior Engineer (Civil)", company: "Staff Selection Commission (SSC)", location: "Pan India", salary: "₹35,400–1,12,400/month", openings: 1200, applicationLink: "https://ssc.gov.in" },
  { title: "SSC JE – Junior Engineer (Electrical)", company: "Staff Selection Commission (SSC)", location: "Pan India", salary: "₹35,400–1,12,400/month", openings: 800, applicationLink: "https://ssc.gov.in" },
  { title: "SSC Stenographer Grade C & D", company: "Staff Selection Commission (SSC)", location: "Pan India", salary: "₹25,500–81,100/month", openings: 2000, applicationLink: "https://ssc.gov.in" },
  { title: "UPSC Civil Services – IAS (Indian Administrative Service)", company: "Union Public Service Commission (UPSC)", location: "Pan India", salary: "₹56,100–2,50,000/month", openings: 180, applicationLink: "https://upsconline.nic.in" },
  { title: "UPSC Civil Services – IPS (Indian Police Service)", company: "Union Public Service Commission (UPSC)", location: "Pan India", salary: "₹56,100–2,50,000/month", openings: 200, applicationLink: "https://upsconline.nic.in" },
  { title: "UPSC Civil Services – IFS (Indian Foreign Service)", company: "Union Public Service Commission (UPSC)", location: "New Delhi / World", salary: "₹56,100–2,50,000/month", openings: 24, applicationLink: "https://upsconline.nic.in" },
  { title: "UPSC Civil Services – IRS (Income Tax)", company: "Union Public Service Commission (UPSC)", location: "Pan India", salary: "₹56,100–2,50,000/month", openings: 80, applicationLink: "https://upsconline.nic.in" },
  { title: "UPSC Civil Services – IRTS (Railway Traffic Service)", company: "Union Public Service Commission (UPSC)", location: "Pan India", salary: "₹56,100–2,50,000/month", openings: 50, applicationLink: "https://upsconline.nic.in" },
  { title: "UPSC NDA – National Defence Academy (Army)", company: "Union Public Service Commission (UPSC)", location: "Pan India (Training: Pune)", salary: "₹56,100+/month", openings: 208, applicationLink: "https://upsconline.nic.in" },
  { title: "UPSC NDA – National Defence Academy (Navy)", company: "Union Public Service Commission (UPSC)", location: "Pan India (Training: Pune)", salary: "₹56,100+/month", openings: 42, applicationLink: "https://upsconline.nic.in" },
  { title: "UPSC NDA – National Defence Academy (Air Force)", company: "Union Public Service Commission (UPSC)", location: "Pan India (Training: Pune)", salary: "₹56,100+/month", openings: 120, applicationLink: "https://upsconline.nic.in" },
  { title: "UPSC CDS – IMA (Indian Military Academy)", company: "Union Public Service Commission (UPSC)", location: "Dehradun, Uttarakhand", salary: "₹56,100+/month", openings: 100, applicationLink: "https://upsconline.nic.in" },
  { title: "UPSC CDS – OTA (Officers Training Academy)", company: "Union Public Service Commission (UPSC)", location: "Chennai, Tamil Nadu", salary: "₹56,100+/month", openings: 175, applicationLink: "https://upsconline.nic.in" },
  { title: "UPSC CAPF – Asst Commandant (BSF/CRPF/CISF)", company: "Union Public Service Commission (UPSC)", location: "Pan India", salary: "₹56,100–1,32,000/month", openings: 253, applicationLink: "https://upsconline.nic.in" },
  { title: "UPSC EPFO – Enforcement Officer/AC", company: "Union Public Service Commission (UPSC)", location: "Pan India", salary: "₹44,900–1,42,400/month", openings: 421, applicationLink: "https://upsconline.nic.in" },
  { title: "UPSC IES – Indian Economic Service", company: "Union Public Service Commission (UPSC)", location: "New Delhi", salary: "₹56,100–1,32,000/month", openings: 15, applicationLink: "https://upsconline.nic.in" },
  { title: "UPSC ISS – Indian Statistical Service", company: "Union Public Service Commission (UPSC)", location: "New Delhi", salary: "₹56,100–1,32,000/month", openings: 30, applicationLink: "https://upsconline.nic.in" },
  { title: "RRB NTPC – Junior Clerk cum Typist", company: "Railway Recruitment Board (RRB)", location: "Pan India", salary: "₹19,900–63,200/month", openings: 8000, applicationLink: "https://indianrailways.gov.in" },
  { title: "RRB NTPC – Accounts Clerk cum Typist", company: "Railway Recruitment Board (RRB)", location: "Pan India", salary: "₹19,900–63,200/month", openings: 5000, applicationLink: "https://indianrailways.gov.in" },
  { title: "RRB NTPC – Traffic Assistant", company: "Railway Recruitment Board (RRB)", location: "Pan India", salary: "₹25,500–81,100/month", openings: 4000, applicationLink: "https://indianrailways.gov.in" },
  { title: "RRB NTPC – Goods Guard", company: "Railway Recruitment Board (RRB)", location: "Pan India", salary: "₹29,200–92,300/month", openings: 3000, applicationLink: "https://indianrailways.gov.in" },
  { title: "RRB NTPC – Senior Commercial cum Ticket Clerk", company: "Railway Recruitment Board (RRB)", location: "Pan India", salary: "₹29,200–92,300/month", openings: 3500, applicationLink: "https://indianrailways.gov.in" },
  { title: "RRB NTPC – Junior Account Assistant cum Typist", company: "Railway Recruitment Board (RRB)", location: "Pan India", salary: "₹25,500–81,100/month", openings: 3000, applicationLink: "https://indianrailways.gov.in" },
  { title: "RRB Group D – Track Maintainer Grade IV", company: "Railway Recruitment Board (RRB)", location: "Pan India", salary: "₹18,000–56,900/month", openings: 20000, applicationLink: "https://indianrailways.gov.in" },
  { title: "RRB Group D – Helper/Assistant (Electrical/Mechanical)", company: "Railway Recruitment Board (RRB)", location: "Pan India", salary: "₹18,000–56,900/month", openings: 12000, applicationLink: "https://indianrailways.gov.in" },
  { title: "RRB JE – Junior Engineer (Signal/Telecom)", company: "Railway Recruitment Board (RRB)", location: "Pan India", salary: "₹35,400–1,12,400/month", openings: 2000, applicationLink: "https://indianrailways.gov.in" },
  { title: "RRB JE – Junior Engineer (Civil/Bridge)", company: "Railway Recruitment Board (RRB)", location: "Pan India", salary: "₹35,400–1,12,400/month", openings: 1800, applicationLink: "https://indianrailways.gov.in" },
  { title: "RRB ALP – Assistant Loco Pilot", company: "Railway Recruitment Board (RRB)", location: "Pan India", salary: "₹19,900–63,200/month", openings: 5000, applicationLink: "https://indianrailways.gov.in" },
  { title: "IBPS PO – Probationary Officer", company: "Institute of Banking Personnel Selection (IBPS)", location: "Pan India (PSB Posting)", salary: "₹41,960–89,890/month", openings: 4455, applicationLink: "https://www.ibps.in" },
  { title: "IBPS Clerk – Junior Associate", company: "Institute of Banking Personnel Selection (IBPS)", location: "Pan India (PSB Posting)", salary: "₹11,765–31,540/month", openings: 7000, applicationLink: "https://www.ibps.in" },
  { title: "IBPS SO – IT Officer (Scale I)", company: "Institute of Banking Personnel Selection (IBPS)", location: "Pan India", salary: "₹23,700–42,020/month", openings: 600, applicationLink: "https://www.ibps.in" },
  { title: "IBPS SO – Agriculture Field Officer", company: "Institute of Banking Personnel Selection (IBPS)", location: "Pan India", salary: "₹23,700–42,020/month", openings: 500, applicationLink: "https://www.ibps.in" },
  { title: "IBPS SO – HR/Personnel Officer", company: "Institute of Banking Personnel Selection (IBPS)", location: "Pan India", salary: "₹23,700–42,020/month", openings: 300, applicationLink: "https://www.ibps.in" },
  { title: "IBPS RRB – Officer Scale I (Rural Bank PO)", company: "Institute of Banking Personnel Selection (IBPS)", location: "Rural Areas Pan India", salary: "₹23,700–42,020/month", openings: 3800, applicationLink: "https://www.ibps.in" },
  { title: "IBPS RRB – Office Assistant (Rural Bank Clerk)", company: "Institute of Banking Personnel Selection (IBPS)", location: "Rural Areas Pan India", salary: "₹15,000–40,000/month", openings: 6000, applicationLink: "https://www.ibps.in" },
  { title: "SBI PO – Probationary Officer", company: "State Bank of India (SBI)", location: "Pan India", salary: "₹41,960–89,890/month", openings: 2000, applicationLink: "https://bank.sbi/careers" },
  { title: "SBI Clerk (Junior Associate)", company: "State Bank of India (SBI)", location: "Pan India", salary: "₹17,900–47,920/month", openings: 8000, applicationLink: "https://bank.sbi/careers" },
  { title: "SBI SO – System Officer (IT)", company: "State Bank of India (SBI)", location: "Pan India", salary: "₹23,700–42,020/month", openings: 400, applicationLink: "https://bank.sbi/careers" },
  { title: "ISRO Scientist/Engineer SC – Computer Science", company: "Indian Space Research Organisation (ISRO)", location: "Bangalore / Multiple Centers", salary: "₹56,100–1,32,000/month", openings: 80, applicationLink: "https://www.isro.gov.in/Careers.html" },
  { title: "ISRO Scientist/Engineer SC – Electronics", company: "Indian Space Research Organisation (ISRO)", location: "VSSC Thiruvananthapuram", salary: "₹56,100–1,32,000/month", openings: 70, applicationLink: "https://www.isro.gov.in/Careers.html" },
  { title: "ISRO Technician B – Fitter/Welder", company: "Indian Space Research Organisation (ISRO)", location: "SDSC SHAR, Sriharikota", salary: "₹18,000–56,900/month", openings: 150, applicationLink: "https://www.isro.gov.in/Careers.html" },
  { title: "DRDO Scientist B – Electronics/ECE", company: "Defence Research & Development Organisation (DRDO)", location: "Hyderabad (DRDL) / Pune (ARDE)", salary: "₹56,100–1,32,000/month", openings: 80, applicationLink: "https://www.drdo.gov.in/drdo/careers" },
  { title: "DRDO Scientist B – Computer Science", company: "Defence Research & Development Organisation (DRDO)", location: "Delhi (DESIDOC) / Bangalore", salary: "₹56,100–1,32,000/month", openings: 60, applicationLink: "https://www.drdo.gov.in/drdo/careers" },
  { title: "DRDO CEPTAM – Technician A (Multi Tasking)", company: "Defence Research & Development Organisation (DRDO)", location: "Pan India (DRDO Labs)", salary: "₹18,000–56,900/month", openings: 300, applicationLink: "https://www.drdo.gov.in/drdo/careers" },
  { title: "DRDO CEPTAM – Senior Technical Assistant B", company: "Defence Research & Development Organisation (DRDO)", location: "Pan India (DRDO Labs)", salary: "₹25,500–81,100/month", openings: 200, applicationLink: "https://www.drdo.gov.in/drdo/careers" },
  { title: "Indian Army – Soldier GD (General Duty)", company: "Indian Army Recruiting Office", location: "Pan India (Open Rally)", salary: "₹21,700–69,100/month", openings: 30000, applicationLink: "https://joinindianarmy.nic.in" },
  { title: "Indian Army – Soldier Technical", company: "Indian Army Recruiting Office", location: "Pan India (Open Rally)", salary: "₹21,700–69,100/month", openings: 5000, applicationLink: "https://joinindianarmy.nic.in" },
  { title: "Indian Army – Soldier Clerk/SKT", company: "Indian Army Recruiting Office", location: "Pan India (Open Rally)", salary: "₹25,500–81,100/month", openings: 3000, applicationLink: "https://joinindianarmy.nic.in" },
  { title: "Indian Air Force – Airman Group X (Technical)", company: "Indian Air Force", location: "Pan India (Airmen Selection Center)", salary: "₹26,900–1,12,400/month", openings: 3000, applicationLink: "https://airmenselection.cdac.in" },
  { title: "Indian Air Force – Airman Group Y (Non-Technical)", company: "Indian Air Force", location: "Pan India (Airmen Selection Center)", salary: "₹21,700–69,100/month", openings: 4000, applicationLink: "https://airmenselection.cdac.in" },
  { title: "Indian Navy – Sailor Senior Secondary Recruit (SSR)", company: "Indian Navy", location: "Pan India", salary: "₹21,700–69,100/month", openings: 3000, applicationLink: "https://www.joinindiannavy.gov.in" },
  { title: "Indian Navy – Matric Recruit (MR) – Cook/Steward", company: "Indian Navy", location: "Pan India", salary: "₹18,000–56,900/month", openings: 1500, applicationLink: "https://www.joinindiannavy.gov.in" },
  { title: "Indian Coast Guard – Navik General Duty", company: "Indian Coast Guard (Ministry of Defence)", location: "Pan India (Maritime States)", salary: "₹21,700–69,100/month", openings: 1000, applicationLink: "https://joinindiancoastguard.cdac.in" },
  { title: "India Post – Postman/Mail Guard", company: "India Post (Department of Posts)", location: "Pan India (Postal Circles)", salary: "₹21,700–69,100/month", openings: 5000, applicationLink: "https://indiapostgdsonline.gov.in" },
  { title: "India Post GDS – Gramin Dak Sevak", company: "India Post (Department of Posts)", location: "Rural India (Postal Divisions)", salary: "₹10,000–14,500/month", openings: 30000, applicationLink: "https://indiapostgdsonline.gov.in" },
  { title: "India Post – Postal Assistant (PA)", company: "India Post (Department of Posts)", location: "Pan India (Postal Circles)", salary: "₹25,500–81,100/month", openings: 3000, applicationLink: "https://indiapostgdsonline.gov.in" },
  { title: "FCI – Assistant Grade III (General)", company: "Food Corporation of India (FCI)", location: "Pan India (FCI Zonal Offices)", salary: "₹19,900–63,200/month", openings: 5000, applicationLink: "https://fci.gov.in/recruitment.php" },
  { title: "FCI – Junior Engineer (Civil/Electrical)", company: "Food Corporation of India (FCI)", location: "Pan India", salary: "₹35,400–1,12,400/month", openings: 500, applicationLink: "https://fci.gov.in/recruitment.php" },
  { title: "NABARD – Development Assistant", company: "National Bank for Agriculture & Rural Development (NABARD)", location: "Pan India", salary: "₹16,900–44,890/month", openings: 100, applicationLink: "https://www.nabard.org/career.aspx" },
  { title: "NABARD – Grade A Officer (Agriculture)", company: "National Bank for Agriculture & Rural Development (NABARD)", location: "Pan India", salary: "₹44,500+/month", openings: 150, applicationLink: "https://www.nabard.org/career.aspx" },
  { title: "RBI Grade B Officer", company: "Reserve Bank of India (RBI)", location: "Pan India (Regional Offices)", salary: "₹55,200+/month", openings: 250, applicationLink: "https://www.rbi.org.in/Scripts/Opportunities.aspx" },
  { title: "RBI Assistant", company: "Reserve Bank of India (RBI)", location: "Pan India (Regional Offices)", salary: "₹20,700–36,580/month", openings: 900, applicationLink: "https://www.rbi.org.in/Scripts/Opportunities.aspx" },
  { title: "ONGC Junior Assistant Technician (JA)", company: "Oil and Natural Gas Corporation (ONGC)", location: "Pan India (Drilling Sites)", salary: "₹21,700–69,100/month", openings: 2000, applicationLink: "https://www.ongcindia.com/wps/wcm/connect/ongcindia/home/career" },
  { title: "ONGC Graduate Trainee – Chemical", company: "Oil and Natural Gas Corporation (ONGC)", location: "Mumbai / Gujarat", salary: "₹44,900–1,42,400/month", openings: 300, applicationLink: "https://www.ongcindia.com/wps/wcm/connect/ongcindia/home/career" },
  { title: "BPCL Management Trainee", company: "Bharat Petroleum Corporation Limited (BPCL)", location: "Pan India (Refineries/HQ)", salary: "₹40,000+/month (stipend during training)", openings: 200, applicationLink: "https://bharatpetroleum.in/Careers.aspx" },
  { title: "HPCL Officer (Operations & Distribution)", company: "Hindustan Petroleum Corporation Limited (HPCL)", location: "Pan India", salary: "₹40,000–1,10,000/month", openings: 400, applicationLink: "https://www.hindustanpetroleum.com/career" },
  { title: "HAL Aircraft Technician", company: "Hindustan Aeronautics Limited (HAL)", location: "Bangalore / Nashik / Lucknow", salary: "₹21,700–69,100/month", openings: 500, applicationLink: "https://hal-india.co.in/Career/M00014" },
  { title: "BEL Probationary Engineer", company: "Bharat Electronics Limited (BEL)", location: "Bangalore / Multiple Cities", salary: "₹40,000–1,14,000/month", openings: 300, applicationLink: "https://bel-india.in/Careers" },
  { title: "BEL Project Engineer", company: "Bharat Electronics Limited (BEL)", location: "Hyderabad / Chennai", salary: "₹35,000–90,000/month", openings: 200, applicationLink: "https://bel-india.in/Careers" },
  { title: "BHEL Engineer Trainee", company: "Bharat Heavy Electricals Limited (BHEL)", location: "Hyderabad / Trichy / Haridwar", salary: "₹40,000+/month", openings: 400, applicationLink: "https://careers.bhel.in" },
  { title: "BHEL Supervisor Trainee", company: "Bharat Heavy Electricals Limited (BHEL)", location: "Pan India (Works)", salary: "₹25,500–81,100/month", openings: 300, applicationLink: "https://careers.bhel.in" },
  { title: "SAIL Management Trainee (Technical)", company: "Steel Authority of India Limited (SAIL)", location: "Bhilai / Durgapur / Rourkela", salary: "₹40,000–1,40,000/month", openings: 400, applicationLink: "https://www.sail.co.in/en/Career-Openings" },
  { title: "CIL Management Trainee (Mining)", company: "Coal India Limited (CIL)", location: "Eastern / Central Coalfields", salary: "₹40,000–1,40,000/month", openings: 350, applicationLink: "https://www.coalindia.in/en-us/people/career.aspx" },
  { title: "GAIL Engineer Trainee", company: "GAIL (India) Limited", location: "Noida / Vadodara / Vijaipur", salary: "₹40,000–1,40,000/month", openings: 250, applicationLink: "https://gailonline.com/recruitment.html" },
  { title: "NLC Junior Engineer Trainee", company: "NLC India Limited (Neyveli Lignite)", location: "Neyveli, Tamil Nadu", salary: "₹35,400–1,12,400/month", openings: 300, applicationLink: "https://www.nlcindia.in/new_website/career/career.htm" },
  { title: "CBI Sub Inspector (UPSC Grade)", company: "Central Bureau of Investigation", location: "New Delhi / Major Cities", salary: "₹35,400–1,12,400/month", openings: 100, applicationLink: "https://cbi.gov.in/recruitment.php" },
  { title: "IB ACIO – Asst Central Intelligence Officer", company: "Intelligence Bureau (Ministry of Home)", location: "Pan India (Sensitive Posts)", salary: "₹25,500–81,100/month", openings: 2000, applicationLink: "https://mha.gov.in/en/recruitment" },
];

const COMMON_ELIGIBILITY: Record<string, string> = {
  IT: "B.Tech/B.E/M.Tech in Computer Science or related field. Relevant years of experience as specified. Strong problem-solving skills and technical knowledge required.",
  NON_IT: "Bachelor's/Master's degree in relevant discipline. Prior work experience preferred. Strong communication and organizational skills required.",
  STATE_GOVT: "Relevant educational qualification as per KPSC norms. Karnataka domicile preferred. Age as per government rules. Knowledge of Kannada mandatory for most posts.",
  CENTRAL_GOVT: "Educational qualification as per recruitment notification. Indian citizenship. Age as per government norms (relaxation for SC/ST/OBC/Ex-SM).",
};

const COMMON_GUIDE: Record<string, string> = {
  IT: "Step 1: Visit the company careers portal (link above)\nStep 2: Register/Login to the career portal\nStep 3: Search for the specific role and location\nStep 4: Upload updated resume (PDF, max 2MB) with relevant experience\nStep 5: Fill the online application form completely\nStep 6: Submit application and note the reference number\nStep 7: Await HR contact for assessment/interview scheduling",
  NON_IT: "Step 1: Visit the company's official career page\nStep 2: Search for the position and create your profile\nStep 3: Upload your resume, cover letter, and relevant certificates\nStep 4: Complete the online application form\nStep 5: Attend telephonic screening if shortlisted\nStep 6: Appear for in-person or video interview\nStep 7: Complete background verification after offer",
  STATE_GOVT: "Step 1: Visit kpsc.kar.nic.in for the official notification\nStep 2: Register on the KPSC portal with your Aadhaar and mobile\nStep 3: Fill the online application form with all required details\nStep 4: Upload required documents: photo, signature, certificates\nStep 5: Pay application fee online (₹200 General, ₹100 SC/ST)\nStep 6: Download acknowledgment receipt for reference\nStep 7: Appear for written examination as per hall ticket\nStep 8: Qualify written exam for physical test / interview (if applicable)\nStep 9: Attend document verification and medical examination",
  CENTRAL_GOVT: "Step 1: Check the official website for the latest notification\nStep 2: Register on the official recruitment portal\nStep 3: Fill the online application form with accurate details\nStep 4: Upload photo and signature in specified format\nStep 5: Pay application fee through online banking/UPI\nStep 6: Download admit card from the official portal\nStep 7: Appear for written examination (CBT/OMR)\nStep 8: Qualify examination for Physical Test/Skill Test (if applicable)\nStep 9: Final document verification and medical examination",
};

function getShift(category: string): "Day" | "Night" | "Full_time" | "Part_time" {
  if (category === "IT") return "Full_time";
  if (category === "NON_IT") return Math.random() > 0.7 ? "Day" : "Full_time";
  return "Day";
}

function getDateRange(category: string): { startDate: string; endDate: string } {
  const bases = [
    { start: "2026-02-01", end: "2026-03-15" }, // Past (Closed)
    { start: "2026-03-01", end: "2026-03-31" }, // Past (Closed)
    { start: "2026-04-01", end: "2026-04-30" }, // Current
    { start: "2026-04-15", end: "2026-05-15" }, // Current
    { start: "2026-05-01", end: "2026-05-31" }, // Future
    { start: "2026-06-01", end: "2026-08-31" }, // Specific: June to August
    { start: "2026-07-01", end: "2026-09-30" }, // Future
  ];
  const idx = Math.floor(Math.random() * bases.length);
  return { startDate: bases[idx].start, endDate: bases[idx].end };
}

function getHrEmail(company: string, _category: string): string {
  return buildDefaultHrEmail(company);
}

export function buildJobRows(
  jobs: Array<{
    title: string; company: string; location: string; salary: string;
    openings: number; applicationLink: string; company2?: string;
  }>,
  category: "IT" | "NON_IT" | "STATE_GOVT" | "CENTRAL_GOVT"
) {
  return jobs.map(j => {
    let { startDate, endDate } = getDateRange(category);
    if (j.title.includes("June-August")) {
      startDate = "2026-06-01";
      endDate = "2026-08-31";
    } else if (j.title.includes("April Fast Track")) {
      startDate = "2026-04-01";
      endDate = "2026-04-30";
    }
    return {
      title: j.title,
      company: j.company,
      category,
      location: j.location,
      shift: getShift(category) as any,
      description: `${j.title} opportunity at ${j.company} in ${j.location}. ${j.company} is seeking qualified professionals to join their team. This role offers competitive compensation of ${j.salary} and an excellent opportunity for career growth in the ${category === "IT" ? "technology" : category === "NON_IT" ? "business" : "government"} sector. You will work with a dynamic team to deliver impactful results and contribute to the organization's mission and goals.`,
      eligibility: COMMON_ELIGIBILITY[category],
      applicationGuide: COMMON_GUIDE[category],
      startDate,
      endDate,
      hrEmail: getHrEmail(j.company, category),
      salary: j.salary,
      openings: j.openings,
      applicationLink: j.applicationLink,
      official_url: j.applicationLink,
    };
  });
}
