import { db } from "@workspace/db";
import { jobsTable, examsTable, studyMaterialsTable } from "@workspace/db/schema";

async function seed() {
  console.log("Seeding database...");

  await db.delete(studyMaterialsTable);
  await db.delete(examsTable);
  await db.delete(jobsTable);

  // ─────────────────────────────────────────
  // IT JOBS
  // ─────────────────────────────────────────
  const jobs = await db.insert(jobsTable).values([
    // ── IT ──────────────────────────────────
    {
      title: "Senior Software Engineer",
      company: "Wipro Technologies",
      category: "IT",
      location: "Bangalore, Karnataka",
      shift: "Full_time",
      description: "We are looking for a Senior Software Engineer to join our dynamic team at Wipro Technologies, Bangalore. You will be responsible for designing, developing, and maintaining high-performance web applications using modern technologies including React, Node.js, and cloud platforms. You will work closely with product managers and designers to deliver world-class digital experiences for global clients.",
      eligibility: "B.Tech/B.E in Computer Science or related field. 4+ years of experience in software development. Strong proficiency in JavaScript, TypeScript, React, and Node.js. Experience with AWS/Azure cloud platforms preferred.",
      applicationGuide: "Step 1: Visit Wipro careers portal at careers.wipro.com\nStep 2: Search for 'Senior Software Engineer' in Bangalore\nStep 3: Create an account or log in with your credentials\nStep 4: Upload your updated resume (PDF format, max 2 MB)\nStep 5: Fill in the application form with complete work experience\nStep 6: Submit your application and save the confirmation number\nStep 7: Await email confirmation within 48 hours from hr@wipro.com",
      startDate: "2026-03-01",
      endDate: "2026-04-30",
      hrEmail: "hr@wipro.com",
      salary: "₹18–28 LPA",
      openings: 12,
    },
    {
      title: "Data Scientist",
      company: "TCS (Tata Consultancy Services)",
      category: "IT",
      location: "Hyderabad, Telangana",
      shift: "Full_time",
      description: "Join TCS's world-class data science team to build AI/ML solutions for Fortune 500 clients across healthcare, BFSI, and retail verticals. You will work on predictive models, NLP systems, and computer vision applications. The role involves working with large datasets, developing machine learning pipelines, and deploying models to production environments.",
      eligibility: "M.Tech/M.Sc in Data Science, Statistics, or Computer Science. 3+ years experience in ML/AI. Proficiency in Python, TensorFlow/PyTorch, and SQL. Experience with NLP or computer vision is a plus.",
      applicationGuide: "Step 1: Go to TCS NextStep portal (nextstep.tcs.com)\nStep 2: Register with a valid email ID and create your profile\nStep 3: Fill in educational and professional details accurately\nStep 4: Upload resume and any AI/ML project certificates\nStep 5: Appear for online assessment (aptitude + technical screening)\nStep 6: Await interview scheduling via email from hr@tcs.com",
      startDate: "2026-03-15",
      endDate: "2026-05-15",
      hrEmail: "hr@tcs.com",
      salary: "₹15–22 LPA",
      openings: 8,
    },
    {
      title: "DevOps Engineer",
      company: "Infosys Limited",
      category: "IT",
      location: "Pune, Maharashtra",
      shift: "Full_time",
      description: "Infosys is seeking an experienced DevOps Engineer to manage and optimize CI/CD pipelines, cloud infrastructure, and containerized deployments. You will work with development teams to automate build, test, and deployment workflows, manage Kubernetes clusters, and ensure high availability of production systems across global client environments.",
      eligibility: "B.Tech/B.E in Computer Science or IT. 3+ years in DevOps/SRE roles. Strong knowledge of Docker, Kubernetes, Jenkins, Terraform. AWS/GCP certification preferred.",
      applicationGuide: "Step 1: Visit infosys.com/careers\nStep 2: Search for 'DevOps Engineer Pune' in the job listings\nStep 3: Register or sign in with your existing account\nStep 4: Apply with updated resume highlighting DevOps projects\nStep 5: Complete online technical screening (MCQ + coding)\nStep 6: Attend virtual technical interview with DevOps team",
      startDate: "2026-04-01",
      endDate: "2026-05-31",
      hrEmail: "hr@infosys.com",
      salary: "₹12–20 LPA",
      openings: 5,
    },
    {
      title: "UI/UX Designer",
      company: "Accenture India",
      category: "IT",
      location: "Chennai, Tamil Nadu",
      shift: "Full_time",
      description: "Accenture needs a creative UI/UX Designer to craft exceptional digital experiences for enterprise clients. You will lead the design of web and mobile applications from wireframes to high-fidelity prototypes, conduct user research, create design systems, and collaborate with engineering teams to implement pixel-perfect interfaces.",
      eligibility: "Bachelor's degree in Design, Computer Science, or related field. 3+ years of UI/UX design experience. Proficiency in Figma, Adobe XD. Portfolio showcasing digital product design required.",
      applicationGuide: "Step 1: Visit accenture.com/in-en/careers\nStep 2: Create an Accenture profile using your email\nStep 3: Apply for the UI/UX Designer role in Chennai\nStep 4: Submit portfolio link (Behance/Dribbble) along with application\nStep 5: Complete design challenge within 3 days of invitation\nStep 6: Attend design review with senior designers",
      startDate: "2026-03-10",
      endDate: "2026-04-25",
      hrEmail: "hr@accenture.com",
      salary: "₹10–18 LPA",
      openings: 6,
    },
    {
      title: "Full Stack Developer (React + Node)",
      company: "HCL Technologies",
      category: "IT",
      location: "Noida, Uttar Pradesh",
      shift: "Full_time",
      description: "HCL Technologies is hiring a Full Stack Developer with hands-on experience in React.js and Node.js to build scalable web applications for global insurance and banking clients. You will own end-to-end development — from database design to RESTful APIs to modern React frontends — working in agile sprint cycles.",
      eligibility: "B.Tech in Computer Science or Information Technology. 2–5 years full stack development experience. Strong proficiency in React.js, Node.js, Express, MongoDB or PostgreSQL. Knowledge of Git, Docker, and CI/CD is required.",
      applicationGuide: "Step 1: Apply at hcltech.com/careers\nStep 2: Select 'Full Stack Developer' role in Noida\nStep 3: Upload your resume with GitHub profile link\nStep 4: Attempt online coding assessment on HackerRank\nStep 5: Clear two technical interview rounds\nStep 6: HR discussion and offer rollout",
      startDate: "2026-04-10",
      endDate: "2026-06-10",
      hrEmail: "careers@hcltech.com",
      salary: "₹10–16 LPA",
      openings: 20,
    },
    {
      title: "Cloud Solutions Architect",
      company: "IBM India",
      category: "IT",
      location: "Bangalore, Karnataka",
      shift: "Full_time",
      description: "IBM India is looking for a Cloud Solutions Architect to design and implement enterprise-grade cloud architectures on IBM Cloud, AWS, and Azure. You will consult with Fortune 500 clients to migrate legacy systems to cloud, optimize costs, ensure security compliance, and drive digital transformation initiatives.",
      eligibility: "B.Tech/M.Tech in Computer Science or related field. 6+ years of experience. AWS/Azure/IBM Cloud certification mandatory. Strong knowledge of microservices, serverless architecture, and cloud security.",
      applicationGuide: "Step 1: Visit ibm.com/employment/in-en\nStep 2: Search for 'Cloud Solutions Architect Bangalore'\nStep 3: Apply online with updated resume and cloud certifications\nStep 4: Complete IBM Kenexa assessment\nStep 5: Three technical interview rounds including architecture design exercise\nStep 6: Final HR discussion and salary negotiation",
      startDate: "2026-03-20",
      endDate: "2026-05-20",
      hrEmail: "hr.india@ibm.com",
      salary: "₹25–40 LPA",
      openings: 4,
    },
    {
      title: "Cybersecurity Analyst",
      company: "Tech Mahindra",
      category: "IT",
      location: "Hyderabad, Telangana",
      shift: "Full_time",
      description: "Tech Mahindra seeks a skilled Cybersecurity Analyst to protect enterprise clients' digital infrastructure. Responsibilities include vulnerability assessment, penetration testing, SIEM monitoring, incident response, and security audits. You will work with global telecom and BFSI clients to maintain robust security postures.",
      eligibility: "B.Tech in Computer Science or Information Security. 3+ years in cybersecurity roles. Certifications: CEH, CISSP, or CompTIA Security+ preferred. Knowledge of SIEM tools, firewalls, and OWASP Top 10.",
      applicationGuide: "Step 1: Visit techmahindra.com/en-in/careers\nStep 2: Search for Cybersecurity Analyst roles\nStep 3: Submit application with certifications\nStep 4: Technical screening on cybersecurity concepts\nStep 5: Practical assessment — identify vulnerabilities in a sandbox\nStep 6: Final managerial round and offer",
      startDate: "2026-04-05",
      endDate: "2026-06-05",
      hrEmail: "hr@techmahindra.com",
      salary: "₹12–22 LPA",
      openings: 9,
    },
    {
      title: "Mobile App Developer (Android/iOS)",
      company: "Mphasis Limited",
      category: "IT",
      location: "Bangalore, Karnataka",
      shift: "Full_time",
      description: "Mphasis is recruiting a Mobile App Developer to build and maintain high-quality Android and iOS applications for fintech clients. You will use React Native or Flutter to deliver cross-platform experiences, integrate payment gateways, and ensure apps meet banking security standards.",
      eligibility: "B.Tech in Computer Science or IT. 2–4 years of mobile development experience. Proficiency in React Native or Flutter, and native Android (Kotlin) or iOS (Swift). Experience with REST APIs and Firebase.",
      applicationGuide: "Step 1: Visit mphasis.com/careers\nStep 2: Search for 'Mobile App Developer Bangalore'\nStep 3: Register and apply with your updated resume\nStep 4: Complete online coding challenge\nStep 5: Two technical interview rounds\nStep 6: HR round and background verification",
      startDate: "2026-05-01",
      endDate: "2026-07-01",
      hrEmail: "talent@mphasis.com",
      salary: "₹8–14 LPA",
      openings: 7,
    },

    // ── NON-IT ──────────────────────────────
    {
      title: "HR Executive",
      company: "Mahindra Group",
      category: "NON_IT",
      location: "Mumbai, Maharashtra",
      shift: "Day",
      description: "Mahindra Group is seeking an HR Executive to manage end-to-end recruitment, employee engagement, and HR operations. Responsibilities include talent acquisition, onboarding, performance management, payroll coordination, and maintaining employee records in HRMS. You will work with department heads to ensure smooth HR processes across the organization.",
      eligibility: "MBA/PGDM in Human Resources. 2–4 years of HR generalist experience. Proficiency in MS Office and HRMS tools (SAP/Workday). Strong communication and interpersonal skills required.",
      applicationGuide: "Step 1: Visit mahindra.com/careers\nStep 2: Search for HR Executive position in Mumbai\nStep 3: Submit application with updated CV and cover letter\nStep 4: Initial HR screening call (30 minutes)\nStep 5: Face-to-face interview with HR Manager\nStep 6: Final round with HR Director and background verification",
      startDate: "2026-03-20",
      endDate: "2026-05-10",
      hrEmail: "hr@mahindra.com",
      salary: "₹5–8 LPA",
      openings: 3,
    },
    {
      title: "Marketing Manager",
      company: "ITC Limited",
      category: "NON_IT",
      location: "Kolkata, West Bengal",
      shift: "Full_time",
      description: "ITC Limited is looking for an experienced Marketing Manager to lead brand strategy, digital marketing campaigns, and market research initiatives for its FMCG division. You will develop go-to-market plans, manage agency partnerships, and drive customer acquisition across multiple channels including digital and traditional media.",
      eligibility: "MBA in Marketing from a reputed institution. 5+ years of marketing experience in FMCG/Consumer goods. Strong analytical skills and data-driven mindset. Experience with digital marketing tools (Google Ads, Meta Ads, HubSpot).",
      applicationGuide: "Step 1: Apply via itcportal.com/careers\nStep 2: Fill the online application form completely\nStep 3: Upload resume and cover letter (PDF)\nStep 4: Written assessment on marketing strategy (online)\nStep 5: Panel interview with Marketing Leadership\nStep 6: Offer negotiation and background verification",
      startDate: "2026-04-05",
      endDate: "2026-06-01",
      hrEmail: "hr@itc.in",
      salary: "₹12–18 LPA",
      openings: 2,
    },
    {
      title: "Operations Coordinator",
      company: "Reliance Industries",
      category: "NON_IT",
      location: "Navi Mumbai, Maharashtra",
      shift: "Day",
      description: "Reliance Industries is hiring an Operations Coordinator to support supply chain, vendor management, and process optimization activities. The role involves coordinating with multiple departments, tracking operational KPIs, preparing MIS reports, and ensuring smooth operational workflows across retail and logistics verticals.",
      eligibility: "Bachelor's degree in Business Administration or Operations Management. 2–3 years in operations/supply chain role. Proficiency in MS Excel and ERP systems (SAP). Strong organizational and analytical skills.",
      applicationGuide: "Step 1: Visit ril.com/careers\nStep 2: Register and search for Operations Coordinator\nStep 3: Submit application and required documents\nStep 4: Initial telephonic screening from HR team\nStep 5: In-person interview at Navi Mumbai office\nStep 6: Medical check-up and background verification",
      startDate: "2026-03-25",
      endDate: "2026-05-20",
      hrEmail: "hr@ril.com",
      salary: "₹6–10 LPA",
      openings: 7,
    },
    {
      title: "Finance Analyst",
      company: "HDFC Bank",
      category: "NON_IT",
      location: "Mumbai, Maharashtra",
      shift: "Full_time",
      description: "HDFC Bank is recruiting a Finance Analyst to support its corporate finance and treasury operations. Responsibilities include financial modeling, budgeting, variance analysis, management reporting, and supporting senior leadership with business insights. You will work with cross-functional teams in a fast-paced banking environment.",
      eligibility: "CA / MBA Finance from a premier institute. 2–4 years of finance/banking experience. Proficiency in MS Excel, financial modeling, and ERP systems. CFA qualification is an advantage.",
      applicationGuide: "Step 1: Visit hdfcbank.com/careers\nStep 2: Search for Finance Analyst role in Mumbai\nStep 3: Register and upload your CA/MBA marksheets with resume\nStep 4: Online aptitude and finance test\nStep 5: Two rounds of panel interviews including a case study\nStep 6: HR discussion, offer letter, and document verification",
      startDate: "2026-04-15",
      endDate: "2026-06-15",
      hrEmail: "careers@hdfcbank.com",
      salary: "₹10–16 LPA",
      openings: 5,
    },
    {
      title: "Supply Chain Manager",
      company: "Hindustan Unilever Limited (HUL)",
      category: "NON_IT",
      location: "Bangalore, Karnataka",
      shift: "Full_time",
      description: "HUL is hiring a Supply Chain Manager to oversee end-to-end supply chain operations for its South India FMCG distribution network. You will manage procurement, warehousing, logistics, and third-party supplier relationships while driving cost optimization and improving OTIF (On Time In Full) metrics.",
      eligibility: "B.Tech + MBA (Supply Chain/Operations) from a reputed institution. 5+ years of supply chain experience in FMCG/Manufacturing. Strong proficiency in SAP MM module. Experience with demand planning and S&OP processes.",
      applicationGuide: "Step 1: Visit careers.unilever.com\nStep 2: Search for Supply Chain Manager roles in India\nStep 3: Apply with complete work history and leadership examples\nStep 4: Online psychometric and situational judgment tests\nStep 5: Virtual case study interview with Supply Chain Director\nStep 6: Final leadership interview and reference checks",
      startDate: "2026-05-01",
      endDate: "2026-07-01",
      hrEmail: "hr@hul.co.in",
      salary: "₹18–28 LPA",
      openings: 3,
    },
    {
      title: "Sales Executive",
      company: "Bajaj Allianz Life Insurance",
      category: "NON_IT",
      location: "Pune, Maharashtra",
      shift: "Full_time",
      description: "Bajaj Allianz Life Insurance is hiring enthusiastic Sales Executives to drive life insurance product sales across Pune and surrounding areas. You will prospect new clients, conduct product presentations, maintain client relationships, and meet monthly sales targets. Extensive training and incentive structure provided.",
      eligibility: "Graduate in any discipline. 1–3 years of sales experience (insurance preferred but not mandatory). Strong communication skills in English, Hindi, and Marathi. Must have a 2-wheeler for field visits.",
      applicationGuide: "Step 1: Apply at bajajallianz.com/about-us/careers.html\nStep 2: Select Sales Executive (Life Insurance) in Pune\nStep 3: Submit application with educational certificates\nStep 4: Telephonic screening with Zonal HR\nStep 5: In-person interview at Pune branch office\nStep 6: Join the 2-week product and sales training program",
      startDate: "2026-03-01",
      endDate: "2026-06-30",
      hrEmail: "hr@bajajallianz.co.in",
      salary: "₹3.5–6 LPA + Incentives",
      openings: 30,
    },
    {
      title: "Content Writer & SEO Specialist",
      company: "Byju's (Think & Learn Pvt Ltd)",
      category: "NON_IT",
      location: "Bangalore, Karnataka",
      shift: "Full_time",
      description: "Byju's is hiring a talented Content Writer and SEO Specialist to create high-quality educational content, blog articles, landing pages, and marketing copy. You will optimize content for search engines, improve organic rankings, conduct keyword research, and collaborate with the product and growth teams to drive traffic.",
      eligibility: "Bachelor's degree in English, Journalism, Communications, or Marketing. 2+ years of content writing and SEO experience. Proficiency in SEO tools (Ahrefs, SEMrush, Google Analytics). Strong command of English grammar and storytelling.",
      applicationGuide: "Step 1: Apply at byjus.com/careers\nStep 2: Search for Content Writer SEO roles in Bangalore\nStep 3: Submit resume and a writing portfolio (3–5 samples)\nStep 4: Content assignment – write a 600-word article in 24 hours\nStep 5: Interview with Content Lead and Growth Manager\nStep 6: HR discussion and offer finalization",
      startDate: "2026-04-01",
      endDate: "2026-05-31",
      hrEmail: "talent@byjus.com",
      salary: "₹6–10 LPA",
      openings: 8,
    },
    {
      title: "Logistics Executive",
      company: "Delhivery Ltd",
      category: "NON_IT",
      location: "Delhi NCR",
      shift: "Day",
      description: "Delhivery is recruiting a Logistics Executive to manage last-mile delivery operations, route planning, and delivery partner coordination for the Delhi NCR hub. You will track shipment metrics, resolve delivery exceptions, coordinate with clients for SLA adherence, and ensure smooth day-to-day hub operations.",
      eligibility: "Bachelor's degree in Commerce, Business Administration, or Logistics. 1–3 years in logistics/e-commerce operations. Proficiency in MS Excel and logistics management tools. Must be comfortable working in a fast-paced warehouse environment.",
      applicationGuide: "Step 1: Visit delhivery.com/careers\nStep 2: Apply for Logistics Executive role in Delhi NCR\nStep 3: Submit your resume and address proof\nStep 4: Telephonic interview with Zonal Operations Head\nStep 5: Field visit/practical assessment at the hub\nStep 6: Offer letter and joining formalities",
      startDate: "2026-04-10",
      endDate: "2026-06-10",
      hrEmail: "talent@delhivery.com",
      salary: "₹3–5 LPA",
      openings: 25,
    },

    // ── STATE GOVT ──────────────────────────
    {
      title: "Junior Engineer (Civil) – PWD",
      company: "Karnataka Public Works Department (PWD)",
      category: "STATE_GOVT",
      location: "Bangalore, Karnataka",
      shift: "Day",
      description: "Karnataka PWD is recruiting Junior Engineers (Civil) for infrastructure and construction project management across Karnataka. Selected candidates will supervise road construction, bridges, government buildings, and drainage projects. Excellent government benefits including housing allowance, medical benefits, LTC, and pension applicable.",
      eligibility: "Diploma or B.E/B.Tech in Civil Engineering. Age: 18–35 years. Must be a Karnataka domicile. KPSC registration required. Knowledge of Kannada is mandatory.",
      applicationGuide: "Step 1: Visit kpsc.kar.nic.in for official notification\nStep 2: Register on KPSC portal with valid ID proof (Aadhaar/Voter ID)\nStep 3: Fill online application form with all educational details\nStep 4: Upload scanned photo, signature, and all certificates\nStep 5: Pay application fee via online banking (₹200 for General, ₹100 SC/ST)\nStep 6: Download application acknowledgment and keep it safe\nStep 7: Appear for written examination as per schedule on admit card\nStep 8: Attend document verification and interview if shortlisted",
      startDate: "2026-04-01",
      endDate: "2026-05-15",
      hrEmail: "recruitment@kpsc.kar.nic.in",
      salary: "₹27,300–52,650/month",
      openings: 250,
    },
    {
      title: "Assistant Professor – Computer Science",
      company: "Karnataka Examinations Authority (KEA)",
      category: "STATE_GOVT",
      location: "Mysore, Karnataka",
      shift: "Day",
      description: "KEA is recruiting Assistant Professors for Government Engineering Colleges across Karnataka for the Computer Science and Engineering department. Responsibilities include teaching undergraduate and postgraduate students, conducting research, mentoring students, and participating in academic activities. Job location varies across Karnataka government colleges.",
      eligibility: "First class M.Tech/M.E in Computer Science. NET/GATE qualified preferred. Age below 40 years. Karnataka domicile required. Teaching experience in any recognized institution is desirable.",
      applicationGuide: "Step 1: Check KEA official portal kea.kar.nic.in\nStep 2: Download and read official notification carefully\nStep 3: Register online and fill the application form\nStep 4: Upload UG/PG mark sheets, NET/GATE scorecard, and experience certificates\nStep 5: Pay fee ₹300 (General) or ₹150 (SC/ST)\nStep 6: Attend written exam and personal interview",
      startDate: "2026-03-15",
      endDate: "2026-04-30",
      hrEmail: "kea@kar.nic.in",
      salary: "₹37,400–67,000/month (AGP ₹6,000)",
      openings: 85,
    },
    {
      title: "Police Sub Inspector (PSI) – Civil",
      company: "Karnataka State Police (KPSC)",
      category: "STATE_GOVT",
      location: "Pan Karnataka",
      shift: "Full_time",
      description: "Karnataka State Police is recruiting Police Sub Inspectors for Civil/Armed Police units across the state. PSIs are responsible for maintaining law and order, leading police constables, conducting investigations, and enforcing the law. The role includes physical duties, fieldwork, and administrative responsibilities within police stations.",
      eligibility: "Graduate in any discipline from a recognized university. Age: 21–28 years (relaxation for SC/ST/OBC). Must clear Physical Efficiency Test (PET): 1600m run in 7 min for men. No criminal record. Karnataka domicile required.",
      applicationGuide: "Step 1: Visit kpsc.kar.nic.in and look for PSI 2026 notification\nStep 2: Register on KPSC portal with Aadhaar and mobile number\nStep 3: Fill online application and choose exam center\nStep 4: Pay ₹250 application fee (SC/ST: ₹100) via online banking\nStep 5: Download hall ticket 15 days before exam\nStep 6: Appear for written test (General Knowledge + Reasoning)\nStep 7: Qualify written test for Physical Efficiency Test (PET)\nStep 8: Medical examination and document verification for final selection",
      startDate: "2026-05-01",
      endDate: "2026-06-30",
      hrEmail: "recruitment@kpsc.kar.nic.in",
      salary: "₹35,100–62,600/month",
      openings: 545,
    },
    {
      title: "Commercial Tax Inspector – Group B",
      company: "Karnataka Commercial Taxes Department",
      category: "STATE_GOVT",
      location: "Bangalore / Mysore / Hubli",
      shift: "Day",
      description: "Karnataka Commercial Taxes Department is hiring Commercial Tax Inspectors to assess, collect, and monitor Goods and Services Tax (GST) and other state taxes. Duties include conducting tax audits, inspecting business premises, verifying financial records, and ensuring taxpayer compliance with state tax laws.",
      eligibility: "Graduate in Commerce, Economics, or Law from a recognized university. Age: 21–35 years. Knowledge of GST and Karnataka state tax laws preferred. Kannada language proficiency (read, write, speak) is mandatory.",
      applicationGuide: "Step 1: Visit kpsc.kar.nic.in for the official notification\nStep 2: Register using a valid Aadhaar-linked mobile number\nStep 3: Fill online application form with academic details\nStep 4: Upload academic certificates and Kannada medium certificate if applicable\nStep 5: Pay ₹200 application fee online\nStep 6: Appear for written examination covering General Knowledge and Tax Laws\nStep 7: Viva-voce (Interview) for shortlisted candidates",
      startDate: "2026-06-01",
      endDate: "2026-07-31",
      hrEmail: "recruitment@kpsc.kar.nic.in",
      salary: "₹28,100–56,900/month",
      openings: 120,
    },
    {
      title: "Agriculture Officer – Krishi Vignana Kendra",
      company: "Karnataka Department of Agriculture",
      category: "STATE_GOVT",
      location: "Rural Karnataka (Posted across 30 districts)",
      shift: "Day",
      description: "The Karnataka Department of Agriculture is hiring Agriculture Officers to implement government schemes like PM-KISAN, Pradhan Mantri Fasal Bima Yojana, and soil health card distribution in rural areas. You will guide farmers on modern farming techniques, organic agriculture, and water conservation practices.",
      eligibility: "B.Sc Agriculture from a recognized agricultural university. Age: 21–35 years. Karnataka domicile mandatory. Knowledge of local language (Kannada and regional dialect). Willingness to work in rural/semi-urban areas.",
      applicationGuide: "Step 1: Check KPSC portal for Agriculture Officer notification\nStep 2: Register and fill online application\nStep 3: Upload B.Sc Agriculture mark sheets and certificates\nStep 4: Pay ₹200 application fee (SC/ST: ₹100)\nStep 5: Appear for KPSC written exam — Agriculture subjects + GK\nStep 6: District-level document verification and posting",
      startDate: "2026-04-15",
      endDate: "2026-06-15",
      hrEmail: "recruitment@kpsc.kar.nic.in",
      salary: "₹25,500–48,000/month",
      openings: 300,
    },
    {
      title: "Nurse (Staff Nurse) – Government Hospitals",
      company: "Karnataka Health Department (DHO)",
      category: "STATE_GOVT",
      location: "Pan Karnataka (All Districts)",
      shift: "Full_time",
      description: "Karnataka Health Department is recruiting Staff Nurses for Government District Hospitals, Taluk Hospitals, and Primary Health Centers (PHCs) across Karnataka. Duties include patient care, administering medications, wound dressing, maintaining patient records, and assisting doctors during procedures.",
      eligibility: "B.Sc Nursing or GNM (General Nursing and Midwifery) from a recognized institution. Registered with Karnataka Nursing Council. Age: 21–40 years. Karnataka domicile preferred. Knowledge of Kannada is mandatory.",
      applicationGuide: "Step 1: Visit kar.nic.in/healthdept for official notification\nStep 2: Register on the state health department portal\nStep 3: Fill application with nursing council registration number\nStep 4: Upload GNM/B.Sc Nursing certificates and Nursing Council ID\nStep 5: Pay ₹200 fee (SC/ST: ₹100) via challan or online\nStep 6: Merit-based selection through marks + interview\nStep 7: Medical fitness test and document verification",
      startDate: "2026-03-10",
      endDate: "2026-05-10",
      hrEmail: "dhs@kar.nic.in",
      salary: "₹22,400–42,500/month",
      openings: 1200,
    },

    // ── CENTRAL GOVT ────────────────────────
    {
      title: "Staff Selection Commission – CGL (Combined Graduate Level)",
      company: "Staff Selection Commission (SSC)",
      category: "CENTRAL_GOVT",
      location: "Pan India (All States)",
      shift: "Full_time",
      description: "SSC CGL 2026 recruitment for various Group-B and Group-C posts in Central Government Ministries, Departments, and Organizations. Posts include Income Tax Inspector, Assistant Section Officer, Auditor, Accountant, Statistical Investigator, Compiler, and more. Excellent career growth with government benefits including DA, HRA, LTC, and pension.",
      eligibility: "Graduate in any discipline from a recognized university. Age: 18–32 years (OBC: 35 years, SC/ST: 37 years). Indian Citizen. Certain posts require specific educational qualifications.",
      applicationGuide: "Step 1: Visit ssc.gov.in for official CGL 2026 notification\nStep 2: Register on SSC portal with valid email and mobile\nStep 3: Fill application form with personal and educational details\nStep 4: Upload photo and signature in JPEG format as specified\nStep 5: Select exam center preferences from available list\nStep 6: Pay fee ₹100 (Female/SC/ST/Ex-Servicemen: Exempt)\nStep 7: Download admit card and appear for Tier 1 CBT (Computer Based Test)\nStep 8: Qualify Tier 1 to appear in Tier 2 (Multiple Papers)\nStep 9: Attend document verification at the SSC regional office",
      startDate: "2026-04-15",
      endDate: "2026-05-30",
      hrEmail: "ssc-cgl@ssc.gov.in",
      salary: "₹29,200–92,300/month (as per post)",
      openings: 14000,
    },
    {
      title: "UPSC Civil Services Examination (IAS/IPS/IFS)",
      company: "Union Public Service Commission (UPSC)",
      category: "CENTRAL_GOVT",
      location: "Pan India (All States)",
      shift: "Full_time",
      description: "UPSC CSE 2026 – The most prestigious examination for recruitment to Indian Administrative Service (IAS), Indian Police Service (IPS), Indian Foreign Service (IFS), and 24+ allied services. Three-stage selection: Preliminary Examination, Mains Examination, and Personality Test (Interview) conducted over approximately 12 months.",
      eligibility: "Graduate degree from any recognized university. Age: 21–32 years (OBC: 35 years, SC/ST: 37 years). Maximum 6 attempts for General category. Indian citizenship mandatory for IAS/IPS/IFS.",
      applicationGuide: "Step 1: Visit upsc.gov.in for CSE 2026 notification\nStep 2: Complete OTR (One Time Registration) on UPSC portal\nStep 3: Fill Detailed Application Form (DAF) with all details\nStep 4: Choose Prelims exam center from available options\nStep 5: Pay ₹100 fee (Women/SC/ST: Exempt)\nStep 6: Download e-Admit card from UPSC website\nStep 7: Appear for Prelims (GS Paper 1 + CSAT Paper 2)\nStep 8: Qualify Prelims and apply for Mains (9 papers)\nStep 9: Personality Test for candidates who qualify Mains",
      startDate: "2026-02-01",
      endDate: "2026-03-20",
      hrEmail: "uscexam@upsc.gov.in",
      salary: "₹56,100–2,50,000/month (IAS Pay Level 10–18)",
      openings: 1056,
    },
    {
      title: "Railway Recruitment Board – Group D Technician",
      company: "Railway Recruitment Board (RRB)",
      category: "CENTRAL_GOVT",
      location: "Pan India (Zone-wise allocation)",
      shift: "Full_time",
      description: "RRB Group D 2026 recruitment for Technician, Track Maintainer, Helper, and Pointsman posts across Indian Railways zones. Selected candidates will maintain railway infrastructure, tracks, electrical systems, and equipment ensuring safe and efficient rail operations across the country.",
      eligibility: "ITI certificate in relevant trade OR 10+2 with Science subjects. Age: 18–36 years (relaxation for reserved categories as per rules). Physical Efficiency Test (PET) mandatory. Must be medically fit as per Railway medical standards.",
      applicationGuide: "Step 1: Visit rrbcdg.gov.in or respective zonal RRB website\nStep 2: Register with Aadhaar-linked mobile number\nStep 3: Fill online application with personal and educational details\nStep 4: Upload photo, signature, and ITI certificate (JPEG format)\nStep 5: Pay fee ₹500 (SC/ST/Ex-SM/PwD/Women: ₹250) online\nStep 6: Download admit card and appear for Computer Based Test (CBT)\nStep 7: Qualify CBT and appear for Physical Efficiency Test (PET)\nStep 8: Document verification and medical examination for final selection",
      startDate: "2026-05-01",
      endDate: "2026-06-30",
      hrEmail: "rrb@indianrailways.gov.in",
      salary: "₹18,000–56,900/month (Pay Level 1–2)",
      openings: 32000,
    },
    {
      title: "IBPS PO – Probationary Officer",
      company: "Institute of Banking Personnel Selection (IBPS)",
      category: "CENTRAL_GOVT",
      location: "Pan India (Bank Branch Posting)",
      shift: "Full_time",
      description: "IBPS PO 2026 recruitment for Probationary Officer posts in participating public sector banks including PNB, Canara Bank, Bank of Baroda, UCO Bank, and others. POs manage branch operations, customer service, credit assessment, loan processing, and team leadership after a 2-year probation period.",
      eligibility: "Graduate in any discipline with minimum 60% marks (55% for SC/ST). Age: 20–30 years (SC/ST: 35 years, OBC: 33 years). Proficiency in the official language of the state applied for. Basic computer knowledge required.",
      applicationGuide: "Step 1: Visit ibps.in for IBPS PO 2026 notification\nStep 2: Register online and fill the application form\nStep 3: Upload scanned photo and signature\nStep 4: Pay ₹850 (SC/ST/PwD: ₹175) application fee online\nStep 5: Download call letter and appear for Prelims (Online CBT)\nStep 6: Qualify Prelims and appear for Main Examination\nStep 7: Shortlisted candidates attend Interview + Group Discussion\nStep 8: Final merit list and bank allotment",
      startDate: "2026-08-01",
      endDate: "2026-09-01",
      hrEmail: "ibps@ibps.in",
      salary: "₹41,960–89,890/month (Basic + DA/HRA)",
      openings: 4455,
    },
    {
      title: "NDA – National Defence Academy",
      company: "Union Public Service Commission (UPSC)",
      category: "CENTRAL_GOVT",
      location: "Pan India (Training at Pune, Maharashtra)",
      shift: "Full_time",
      description: "UPSC NDA 2026 examination for joining the Indian Army, Indian Navy, and Indian Air Force as Officer cadets. After selection and training at NDA, Pune, candidates receive commissions as Lieutenant (Army), Sub Lieutenant (Navy), or Flying Officer (Air Force). Prestigious career with excellent growth prospects.",
      eligibility: "10+2 (Science with Physics and Maths for Air Force/Navy). Age: 16.5–19.5 years. Male Indian citizens only. Must be unmarried. Good physical and medical fitness as per SSB standards.",
      applicationGuide: "Step 1: Visit upsc.gov.in for NDA 2026 (I or II) notification\nStep 2: Register on UPSC OTR portal\nStep 3: Fill DAF-1 application form online\nStep 4: Pay ₹100 fee (SC/ST/Sons of JCOs: Exempt)\nStep 5: Download admit card for written exam\nStep 6: Appear for NDA written exam (Mathematics + General Ability Test)\nStep 7: Qualify written exam and attend SSB (Service Selection Board) interview\nStep 8: Medical examination at Military Hospital\nStep 9: Join NDA training academy after merit list",
      startDate: "2026-01-15",
      endDate: "2026-02-28",
      hrEmail: "uscexam@upsc.gov.in",
      salary: "₹56,100+ during training, ₹69,400/month on commission",
      openings: 400,
    },
    {
      title: "ISRO Scientist/Engineer – SC",
      company: "Indian Space Research Organisation (ISRO)",
      category: "CENTRAL_GOVT",
      location: "Bangalore (ISRO HQ) / Multiple Centers",
      shift: "Full_time",
      description: "ISRO is recruiting Scientist/Engineers (SC) for its prestigious space research missions including satellite development, launch vehicle design, and ground station operations. Selected candidates work on cutting-edge technologies including Gaganyaan (Human Space Mission), Chandrayaan, and commercial satellite launches.",
      eligibility: "First class B.E/B.Tech in Mechanical, Electronics, Computer Science, Electrical, or related engineering branches from a recognized university. GATE score preferred. Age below 35 years. Indian citizenship mandatory.",
      applicationGuide: "Step 1: Visit isro.gov.in for Scientist/Engineer notification\nStep 2: Register on ISRO recruitment portal\nStep 3: Fill application form with GATE scorecard details\nStep 4: Upload all engineering certificates and transcripts\nStep 5: Pay ₹100 fee (SC/ST/PwD: Exempt)\nStep 6: Shortlisting based on GATE score and academic performance\nStep 7: Interview at respective ISRO center\nStep 8: Medical fitness examination and background verification",
      startDate: "2026-06-01",
      endDate: "2026-07-31",
      hrEmail: "recruitment@isro.gov.in",
      salary: "₹56,100–1,32,000/month (Level 10)",
      openings: 223,
    },
    {
      title: "SSC CHSL – Combined Higher Secondary Level",
      company: "Staff Selection Commission (SSC)",
      category: "CENTRAL_GOVT",
      location: "Pan India",
      shift: "Full_time",
      description: "SSC CHSL 2026 recruitment for Lower Division Clerk (LDC), Junior Secretariat Assistant (JSA), Postal Assistant (PA), Sorting Assistant (SA), and Data Entry Operator (DEO) posts in various Central Government Ministries, Departments, and Organizations. Good government job with stability and perks.",
      eligibility: "10+2 (Intermediate) from any recognized board. Age: 18–27 years (SC/ST: 32 years, OBC: 30 years). Typing speed: 35 WPM (English) or 30 WPM (Hindi) for LDC/JSA. Data Entry speed: 8,000 keystrokes per hour for DEO.",
      applicationGuide: "Step 1: Visit ssc.gov.in for CHSL 2026 official notification\nStep 2: Register on SSC portal with 10+2 marksheet details\nStep 3: Fill application form with post preferences\nStep 4: Pay ₹100 fee (Women/SC/ST/Ex-SM/ESM: Exempt)\nStep 5: Download admit card for Tier-1 CBT exam\nStep 6: Appear for Tier-1 (Quantitative Aptitude + GK + English + Reasoning)\nStep 7: Qualify Tier-1 for Tier-2 (Skill Test/Typing Test)\nStep 8: Document verification at SSC regional office",
      startDate: "2026-03-01",
      endDate: "2026-04-15",
      hrEmail: "ssc-chsl@ssc.gov.in",
      salary: "₹19,900–63,200/month (Pay Level 2–4)",
      openings: 6000,
    },
    {
      title: "Defence Research Scientist – DRDO",
      company: "Defence Research & Development Organisation (DRDO)",
      category: "CENTRAL_GOVT",
      location: "Delhi / Pune / Hyderabad / Bangalore",
      shift: "Full_time",
      description: "DRDO is recruiting Scientists 'B' (Entry Level) through CEPTAM examination for its research laboratories across India. Scientists work on indigenous defence technologies including missiles (Agni, Brahmos), radar systems, electronic warfare equipment, and advanced materials for Indian Armed Forces.",
      eligibility: "First class M.Sc (Physics/Chemistry/Mathematics) or B.E/B.Tech in relevant engineering disciplines. GATE qualified candidates preferred. Age: 18–28 years (SC/ST: 33 years). Indian citizenship is mandatory.",
      applicationGuide: "Step 1: Visit drdo.gov.in/drdo/careers for CEPTAM 2026 notification\nStep 2: Register on DRDO CEPTAM portal with valid email\nStep 3: Fill online application with all educational details\nStep 4: Upload photo, signature, and M.Sc/B.Tech certificates\nStep 5: Pay ₹100 application fee (Women/SC/ST: Exempt)\nStep 6: Appear for Tier-1 CBT (Objective Type)\nStep 7: Appear for Tier-2 (Descriptive/Practical) if shortlisted\nStep 8: Interview with DRDO panel and security clearance",
      startDate: "2026-07-01",
      endDate: "2026-08-31",
      hrEmail: "recruitment@drdo.gov.in",
      salary: "₹56,100–1,32,000/month (Level 10 Pay Matrix)",
      openings: 167,
    },
  ]).returning();

  console.log(`Inserted ${jobs.length} jobs`);

  const exams = await db.insert(examsTable).values([
    {
      name: "PG-CET M.Tech",
      fullName: "Post Graduate Common Entrance Test – M.Tech 2026 (Karnataka)",
      description: "KEA PG-CET M.Tech 2026 is conducted for admission to M.Tech, M.E, M.Arch, and M.Plan postgraduate programs in government, aided, and private engineering colleges across Karnataka. The CBT tests candidates on discipline-specific subjects (Civil, Mechanical, Electronics, Computer Science, etc.) relevant to their chosen PG specialization.",
      examDate: "2026-06-15",
      applicationStartDate: "2026-04-01",
      applicationEndDate: "2026-05-10",
      applyLink: "https://kea.kar.nic.in/pgcet2026",
      eligibility: "Recognized B.E/B.Tech degree in relevant engineering branch with minimum 50% aggregate marks (45% for SC/ST candidates). Final year students may provisionally apply. Karnataka domicile OR studied in Karnataka for at least 7 years. Valid GATE score is an advantage for admission to top government colleges.",
      applicationGuide: "Step 1: Visit kea.kar.nic.in and download PG-CET M.Tech 2026 official notification\nStep 2: Register using a valid email ID and mobile number on the KEA portal\nStep 3: Fill the online application form — personal, educational, category, and specialization details\nStep 4: Upload scanned passport-size photo (max 50KB, JPEG) and signature (max 30KB)\nStep 5: Select your preferred exam center from the available list in Karnataka\nStep 6: Pay application fee online: ₹650 (General/OBC), ₹500 (SC/ST/Category-1)\nStep 7: Submit application and download PDF acknowledgment for future reference\nStep 8: Download Hall Ticket from KEA portal 10 days before the exam date\nStep 9: Appear for Computer-Based Test (CBT) — 100 questions, 90 minutes\nStep 10: Check results on KEA portal and participate in online counseling with required documents",
      officialWebsite: "https://kea.kar.nic.in",
    },
    {
      name: "PG-CET MBA",
      fullName: "Post Graduate Common Entrance Test – MBA 2026 (Karnataka)",
      description: "Karnataka PG-CET MBA 2026 conducted by KEA for admission to 2-year MBA programs across top business schools in Karnataka. The exam tests Verbal Ability, Quantitative Aptitude, Logical Reasoning, and General Awareness. Also accepted by several prominent private B-schools in Bangalore, Mysore, and Hubli.",
      examDate: "2026-06-20",
      applicationStartDate: "2026-04-05",
      applicationEndDate: "2026-05-15",
      applyLink: "https://kea.kar.nic.in/mba2026",
      eligibility: "Any recognized Bachelor's degree with minimum 50% marks (45% for SC/ST/OBC-I/Cat-1). Final year students eligible to apply provisionally. Age no bar for most colleges. Karnataka domicile preferred but not mandatory for private business schools.",
      applicationGuide: "Step 1: Visit kea.kar.nic.in and check MBA PG-CET 2026 notification\nStep 2: Create a new KEA account using your email ID\nStep 3: Select 'PGCET MBA 2026' from the available exam list\nStep 4: Complete all sections — personal details, academic information, reservation category\nStep 5: Upload required documents: 10th marksheet, 12th marksheet, degree certificates (JPEG/PDF)\nStep 6: Pay application fee online: ₹650 (General), ₹500 (SC/ST/Category-1)\nStep 7: Submit application and note your Application Reference Number\nStep 8: Download Hall Ticket from KEA portal 1 week before exam date\nStep 9: Appear for MBA PGCET exam — 100 questions, 90 minutes (no negative marking)\nStep 10: Check results, participate in KEA centralized counseling, and get college allotment",
      officialWebsite: "https://kea.kar.nic.in",
    },
    {
      name: "PG-CET MCA",
      fullName: "Post Graduate Common Entrance Test – MCA 2026 (Karnataka)",
      description: "KEA PG-CET MCA 2026 for admission to 2-year MCA (Master of Computer Applications) programs in Karnataka government and private engineering colleges. Tests candidates on Mathematics, Computer Science fundamentals, and Analytical Ability. MCA graduates are highly sought after in IT industry.",
      examDate: "2026-06-18",
      applicationStartDate: "2026-04-05",
      applicationEndDate: "2026-05-15",
      applyLink: "https://kea.kar.nic.in/mca2026",
      eligibility: "Bachelor's degree in BCA, B.Sc Computer Science, or any degree with Mathematics as a subject. Minimum 50% aggregate marks (45% for SC/ST). Must have studied Mathematics at 10+2 or degree level. Karnataka domicile or studied in Karnataka for 7+ years.",
      applicationGuide: "Step 1: Visit kea.kar.nic.in and download MCA PG-CET 2026 brochure\nStep 2: Register on KEA portal with valid email and phone number\nStep 3: Select 'PGCET MCA 2026' from the exam list\nStep 4: Fill the application form with BCA/B.Sc details and marks\nStep 5: Upload photo, signature, degree certificates, and Mathematics certificate\nStep 6: Pay ₹650 (General) or ₹500 (SC/ST) application fee via net banking/UPI\nStep 7: Submit and download acknowledgment\nStep 8: Download Hall Ticket and appear for the CBT exam\nStep 9: Results declared on KEA portal — participate in online counseling",
      officialWebsite: "https://kea.kar.nic.in",
    },
  ]).returning();

  console.log(`Inserted ${exams.length} exams`);

  await db.insert(studyMaterialsTable).values([
    // M.Tech Materials
    {
      examId: exams[0].id,
      title: "M.Tech Engineering Mathematics – Complete Study Notes",
      subject: "Engineering Mathematics",
      type: "Notes",
      description: "Comprehensive study notes covering Calculus, Linear Algebra, Differential Equations, Numerical Methods, and Transforms. Includes solved examples and shortcuts for PG-CET preparation.",
      url: "https://study.kea.kar.nic.in/mtech/maths-notes.pdf",
    },
    {
      examId: exams[0].id,
      title: "Data Structures & Algorithms – Full Video Lecture Series",
      subject: "Computer Science",
      type: "Video",
      description: "Complete video course covering Arrays, Linked Lists, Trees, Graphs, Sorting, Searching, Dynamic Programming, and their time/space complexity. Ideal for M.Tech CSE PG-CET.",
      url: "https://study.kea.kar.nic.in/mtech/dsa-lectures",
    },
    {
      examId: exams[0].id,
      title: "M.Tech PG-CET Previous 10 Years Question Papers with Solutions",
      subject: "All Engineering Subjects",
      type: "PDF",
      description: "Collection of last 10 years M.Tech PG-CET Karnataka question papers with complete answer keys and detailed solutions by subject experts. Covers all engineering branches.",
      url: "https://study.kea.kar.nic.in/mtech/prev-papers.pdf",
    },
    {
      examId: exams[0].id,
      title: "M.Tech PG-CET Full Mock Test Series 2026 (20 Tests)",
      subject: "All Subjects",
      type: "Practice_Test",
      description: "20 full-length mock tests simulating actual PG-CET M.Tech exam pattern (100 questions, 90 minutes). Includes auto-evaluation, percentile ranking, and detailed performance analytics.",
      url: "https://study.kea.kar.nic.in/mtech/mock-tests",
    },
    {
      examId: exams[0].id,
      title: "Signals & Systems – Complete Notes for ECE PG-CET",
      subject: "Electronics Engineering",
      type: "Notes",
      description: "In-depth notes on Signals and Systems including Fourier Analysis, Z-Transform, Laplace Transform, Sampling Theorem, and Filter Design for ECE branch PG-CET candidates.",
      url: "https://study.kea.kar.nic.in/mtech/signals-notes.pdf",
    },
    {
      examId: exams[0].id,
      title: "Structural Analysis & Design – Civil Engineering PG-CET Notes",
      subject: "Civil Engineering",
      type: "PDF",
      description: "Detailed notes on Structural Analysis (trusses, beams, frames), RCC Design, Steel Design, Soil Mechanics, and Fluid Mechanics for Civil Engineering PG-CET.",
      url: "https://study.kea.kar.nic.in/mtech/civil-notes.pdf",
    },
    {
      examId: exams[0].id,
      title: "Thermodynamics & Machine Design – Mechanical PG-CET",
      subject: "Mechanical Engineering",
      type: "Notes",
      description: "Comprehensive notes for Mechanical Engineering PG-CET covering Thermodynamics, Heat Transfer, Fluid Mechanics, Theory of Machines, and Machine Design with solved numericals.",
      url: "https://study.kea.kar.nic.in/mtech/mech-notes.pdf",
    },
    // MBA Materials
    {
      examId: exams[1].id,
      title: "MBA PGCET – Quantitative Aptitude Complete Workbook",
      subject: "Quantitative Aptitude",
      type: "PDF",
      description: "Chapter-wise workbook with 500+ solved problems on Arithmetic, Algebra, Geometry, Percentage, Profit & Loss, Time-Speed-Distance, and Data Interpretation for MBA PGCET.",
      url: "https://study.kea.kar.nic.in/mba/qa-workbook.pdf",
    },
    {
      examId: exams[1].id,
      title: "Verbal Ability & Reading Comprehension – MBA PGCET Video Course",
      subject: "Verbal Ability",
      type: "Video",
      description: "Full video course on English grammar, vocabulary building, reading comprehension strategies, verbal reasoning, and para-jumbles for MBA PGCET preparation.",
      url: "https://study.kea.kar.nic.in/mba/verbal-course",
    },
    {
      examId: exams[1].id,
      title: "General Awareness – Current Affairs 2025–26 for MBA PGCET",
      subject: "General Awareness",
      type: "Notes",
      description: "Monthly current affairs compilations, static GK notes covering History, Geography, Economy, Science & Technology, and National/International events relevant to MBA PGCET GK section.",
      url: "https://study.kea.kar.nic.in/mba/current-affairs.pdf",
    },
    {
      examId: exams[1].id,
      title: "MBA PGCET Full Mock Test Series (15 Tests) + Previous Papers",
      subject: "All Subjects",
      type: "Practice_Test",
      description: "15 full-length MBA PGCET mock tests with previous 5 years actual question papers. Detailed answer explanations, time management strategies, and section-wise performance analytics.",
      url: "https://study.kea.kar.nic.in/mba/mock-tests",
    },
    {
      examId: exams[1].id,
      title: "Logical Reasoning & Analytical Ability – MBA PGCET Notes",
      subject: "Logical Reasoning",
      type: "Notes",
      description: "Comprehensive notes on Logical Reasoning covering Blood Relations, Syllogisms, Coding-Decoding, Seating Arrangements, Puzzles, Data Sufficiency, and Critical Reasoning for MBA PGCET.",
      url: "https://study.kea.kar.nic.in/mba/reasoning-notes.pdf",
    },
    // MCA Materials
    {
      examId: exams[2].id,
      title: "MCA PG-CET Mathematics – Complete Syllabus Notes",
      subject: "Mathematics",
      type: "Notes",
      description: "Full syllabus notes for MCA PG-CET Mathematics covering Algebra, Calculus, Probability & Statistics, Matrices, Set Theory, Number System, and Mathematical Logic with solved examples.",
      url: "https://study.kea.kar.nic.in/mca/maths-notes.pdf",
    },
    {
      examId: exams[2].id,
      title: "Computer Science Fundamentals – MCA PG-CET Video Lectures",
      subject: "Computer Science",
      type: "Video",
      description: "Video lecture series covering C Programming, Data Structures, Database Management, Operating Systems, Computer Networks, and Software Engineering concepts for MCA PG-CET preparation.",
      url: "https://study.kea.kar.nic.in/mca/cs-lectures",
    },
    {
      examId: exams[2].id,
      title: "MCA PG-CET Previous 8 Years Question Papers",
      subject: "All Subjects",
      type: "PDF",
      description: "Last 8 years MCA PGCET Karnataka question papers with complete solutions and topic-wise analysis. Helps identify important topics and understand exam pattern.",
      url: "https://study.kea.kar.nic.in/mca/prev-papers.pdf",
    },
    {
      examId: exams[2].id,
      title: "MCA PG-CET Practice Test Series (10 Full Tests)",
      subject: "All Subjects",
      type: "Practice_Test",
      description: "10 full-length MCA PGCET practice tests with Mathematics + Computer Science + Analytical Ability sections. Includes performance tracking and weak area identification.",
      url: "https://study.kea.kar.nic.in/mca/mock-tests",
    },
  ]);

  console.log("Seed data inserted successfully!");
  console.log(`Total jobs: ${jobs.length}, Exams: ${exams.length}`);
}

seed()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
